spicetify/cli

install.ps1
Fixing #121, #116, #25 
Using the if/else instead of [requirement header](https://docs.microsoft.com/pt-br/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-5.1#-version-nn), because the message is better for the user.
`$PSMinVersion = 3` is because the `Invoke-WebRequest` cmdlet is on [PowerShell 3+](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6#description).
And changed the break line to `'n` instead of new `Write-Host` blank line.
=> Fixing Powershell install file requirement

src/utils/utils.go
This makes it work for when `spicetify` is symlinked more than once.
=> Resolve recursive symlink

Extensions/trashbin.js
Prior to this PR, Trashbin appears differently from the rest of the items in the context menu, capitalization wise. [Image](https://i.imgur.com/hSC960Z.png)
=> Improper capitalization fix on Trashbin

Extensions/fullAppDisplay.js
I think that the "full app display" extension should open in fullscreen. I made two little changes to request and exit fullscreen, I saw in the zlink.bundle.js file that these are the methods used by the Spotify fullscreen functionality.
=> Open window in fullscreen in fullAppDisplay.js

Extensions/fullAppDisplay.js
Fixed Full App Display extension rendering "undefined" instead of the artist name when the artist name was missing from the track metadata (which seems to be happening for some **podcasts**). 
Will skip rendering "undefined" now and render nothing instead. See the screenshots attached below.
Before the fix:
After the fix:
=> Fixed: Full App Display extension rendering "undefined" artist name

Extensions/fullAppDisplay.js
Fixes #312
Found that Spicetify.Player.getDuration() doesn't immediately update to the new song length after changing track so added a delay in
Delay could be lowered by more than 20ms but wasn't sure how long it needs to be delayed for, so the getDuration performs properly
=> fullAppDisplay.js: Fix song duration after skipping

Extensions/newRelease.js
First thank you for making this amazing program!
This is my first contribution to this project so I'm sorry if I've made any mistakes.
This PR allows the newReleases.js extension to show Podcasts only. I didn't want all the new releases information because I use the Release Radar every week but I thought that having new podcast information could be useful!
I have also added an Ignore All option to clear all new release notifications.
Let me know if there is anything that needs to be fixed.
=> newReleases.js: Show Podcasts only and Ignore All

jsHelper/spicetifyWrapper.js
Noticed while writing an extension that needed to deregister a created context menu item in some situations that the function was using a .remove method which does not exist on a Set object. This change switches it to the delete method so that deregister does not error now.
Console error when attempting to deregister on version 1.2.1 for reference:
```
TypeError: itemList.remove is not a function
at Item.deregister (spicetifyWrapper.js:1527)
at extension.js:126
```
=> fix ContextMenu deregister function, Set does not have a remove method

Extensions/fullAppDisplay.js
I added smooth fading for the fullAppDisplay extension since a song change flickered for a short period while loading the image. This is done by preloading the new image and updating the actual image source 0.5s later as well as adding a background transition.
=> Fade album art and background image in fullAppDisplay extension

Extensions/fullAppDisplay.js
The end of scope for controls in html is misplaced, making the progress bar length be on the same size as the text above if controls aren't enabled.
Before :
After :
=> FullAppDisplay : Fix progress bar length when controls aren't enabled

README.md
Updated Wiki with the legacy installation instructions ([Installation](https://github.com/khanhas/spicetify-cli/wiki/Installation)).
=> Moved Legacy Instructions to the Wiki

Extensions/loopyLoop.js, jsHelper/spicetifyWrapper.js, src/apply/apply.go, src/preprocess/preprocess.go
This fixes multiple major hooks which were broken, the second step that #870 was missing. This PR includes #870 and solves #845.
I have tested and ran this on the newest Spotify, it works very well.
With a build of this PR Spotify should display properly again.
https://github.com/itsmeowForks/spicetify-cli/releases/tag/v2.5.0-patch4
- `Spicetify.React`
- `Spicetify.Platform`
- `Spicetify.Player.getProgress()`
- `Spicetify.Player.getProgressPercent()`
- `Spicetify.ReactComponent.ContextMenu`
- `Spicetify.ReactComponent.RightClickMenu`
- `Spicetify.ReactComponent.Menu`
- Remove star wars easter egg
- disable_sentry (**This is completely removed**, regardless of config settings, as of patch4. Disabling this is no longer necessary)
- disable_logging
- `Spicetify.Menu`
- …
=> Fix multiple hooks and extensions breaking on new Spotify (Solves #845)

spicetify.go, src/cmd/backup.go, src/cmd/cmd.go, src/cmd/upgrade.go, src/preprocess/preprocess.go, src/utils/vcs.go
Will now only pull from highest minor version tag (ex: 2.6.x) instead of master branch, allowing for moderate backwards compatibility. This change also makes the development builds (ones without a version tag) use local CSS mappings only, for convenience.
=> Add minor version tag support for CSS mappings

CustomApps/lyrics-plus/Utils.js, CustomApps/lyrics-plus/index.js, src/apply/apply.go, src/preprocess/preprocess.go
Fixes #1029 #1020 #980 #983 #989 #1003 #1039 #1022
- Error: Custom React App Symbols not found
- `Spicetify.React`
- `Spicetify.Platform`
- `Spicetify.ReactComponent.RightClickMenu`
- `Spicetify.ReactComponent.ContextMenu`
- `Spicetify.ReactComponent.Menu`
- Lyrics Plus (changes in internal APIs)
- `Spicetify.Menu`
- CSS mapping issues
On another note, the list of broken hooks from #945 under `Spicetify.ReactComponent` has fixed itself, so that's one less thing to worry about.
=> Fix for Spotify 1.1.67

jsHelper/spicetifyWrapper.js
`Player` hook structure changed and broke the `getProgress` function, fixed it by using another available function to calculate the progress.
Tested on latest Spotify version;  1.1.68
=> fix: type error in getProgress

jsHelper/spicetifyWrapper.js
Sometimes the popup hides behind UI after changing something. This fixes that.
=> Fix: Popup hiding behind UI without closing

CustomApps/lyrics-plus/Pages.js, Extensions/popupLyrics.js, jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Fixes #1076
Fixes #1062
- `Spicetify.ReactComponent.ContextMenu` and `Spicetify.ReactComponent.RightClickMenu` hooks (This fixes Lyrics Plus React minified error)
- Lyrics Plus progress issue
- Workaround for addProgressListener being removed
- Popup lyrics background being black (bug introduced in 116a5b4c9053b8c2287de139bf8e4f7ea3d9fadd)
=> Fix for Spotify 1.1.68

CustomApps/lyrics-plus/Utils.js, CustomApps/lyrics-plus/index.js, CustomApps/new-releases/Card.js, CustomApps/reddit/Card.js, Extensions/bookmark.js, Extensions/keyboardShortcut.js, Extensions/popupLyrics.js, Extensions/shuffle+.js, globals.d.ts, jsHelper/spicetifyWrapper.js, src/apply/apply.go, src/preprocess/preprocess.go
Fixes #1112
This one's a doozy
- **BREAKING:** Removes `Spicetify.PlaybackControl`
- **BREAKING:** Removes hook `Spicetify.Player.origin2`
- Adds `Spicetify.Player.playUri(uri, context, options)` (replacement for `Spicetify.PlaybackControl.playUri`)
- Fixes Lyrics Plus queue callback
- Fixes New Releases/Reddit Card play button
- Fixes `bookmark.js` play seeking
- Improves popupLyrics error messaging
- Fixes `shuffle+.js` play injection
- Fixes `Spicetify.Queue`
- Updates `Spicetify.test()` to reflect actual contents of Spicetify object
- Adds additional checks to `Spicetify.test()` for new contents
- Fixes `Spicetify.addToQueue` and `Spicetify.removeFromQueue`
- Fixes hook `Spicetify._sidebarItemToClone`
- Fixes hook `Spicetify._cloneSidebarItem`
- Fixes hook `Spicetify.Platform`
- Adds …
=> Fix for 1.1.69

src/preprocess/preprocess.go
Fixes #1204
This changes the `Spicetify.React` hook, and is fully functional on Spotify 1.1.71.
It is also backwards compatible with 1.1.69, as the regex matches both versions.
=> Fix for 1.1.71

jsHelper/spicetifyWrapper.js
Hi!
While working on a custom extension I've noticed that one cannot create nested submenus in context menu. Everything that are defined deeper than level 2 was simply ignored. The PR contains a fix for that.
Given extension:
```javascript
(function Test(){
if (!(Spicetify.ContextMenu)) {
setTimeout(Test, 1000);
return;
}
const subMenu = new Spicetify.ContextMenu.SubMenu(
"Test_1",
[
new Spicetify.ContextMenu.Item("Test_1.1", (uris) => {}, (uris) => true), 
new Spicetify.ContextMenu.SubMenu(
"Test_1.2",
[
new Spicetify.ContextMenu.Item("Test_1.2.1", (uris) => {}, (uris) => true),
new Spicetify.ContextMenu.Item("Test_1.2.2", (uris) => {}, (uris) => true),
new Spicetify.ContextMenu.SubMenu(
"Test_1.2.3",
[
new Spicetify.ContextMenu.Item("Test_1.2.3.1", (uris) => {}, (uris) => true),
new …
```
=> Spicetify.ContextMenu improvement: Add support for arbitrary nesting levels in context menus

css-map.json
I think this is how you're supposed to do it? It should fix this issue with the podcast card showing up in search for my extension https://github.com/theRealPadster/spicetify-hide-podcasts/issues/23
=> Add new css mapping for x-categoryCard-CategoryCard

css-map.json
Fix css mapping for the search input on v1.1.74
Related to: https://github.com/theRealPadster/spicetify-hide-podcasts/issues/23
=> Update mapping for .x-searchInput-searchInputInput

css-map.json
CSS map update for 'queue-tabBar-header' class name. "OEFWODerafYHGp09iLlA" => "queue-tabBar-header"
Related to the Podcasts tab (Your Library page) issue in hidePodcasts extension:
https://github.com/theRealPadster/spicetify-hide-podcasts/issues/24
=> CSS map: update 'queue-tabBar-header'

install.ps1, install.sh, install_curl.ps1
After opening https://github.com/afonsojramos/spicetify-docs/pull/11 the question of whether or not adding to path on Linux was happening at the `install.sh` script was raised. After a quick look at it, it did seem that it was not happening.
This PR, in theory, fixes it, however, I do not have a full linux machine so if anyone could test this I'd be grateful, otherwise, I'll try to test on a VM, but I haven't had much time lately.
I took two Stack Overflow threads into consideration ([#1](https://stackoverflow.com/a/20054809) and [#2](https://superuser.com/a/183980)), which is why I set the path in `.profile`.
Tagging @theRealPadster and @CharlieS1103 for visibility.
=> Add `spicetify` to `$PATH` on linux

install.sh
This adds `spicetify` to the `$PATH` for the Fish shell. 
I also added the shell to the echo line, for people who have more than one shell rc file. This way it doesn't output the same message multiple times, which could be confusing. 
Reference: https://fishshell.com/docs/current/faq.html#how-do-i-run-a-command-every-login-what-s-fish-s-equivalent-to-bashrc-or-profile
=> Add `spicetify` to `$PATH` for Fish shell

css-map.json
This class is broken since spotify `v1.1.76.447`, and the cause of https://github.com/JulienMaille/dribbblish-dynamic-theme/issues/153
Here is a screenshot of the DOM tree:
I'd also map the child elements, but I don't know the actual class names since they're not used in my scripts.
=> CSS map: update `main-rootlist-wrapper`

jsHelper/expFeatures.js
This PR fixes an error caused by setting a property on `activeProperties` that doesn't exist (anymore?). The property was retrieved from localStorage. In my case the key was '58'.
It also fixes https://github.com/khanhas/spicetify-cli/issues/1417. The experimental features didn't render anymore, because of outdated use of properties on the `resolver` object.
I was testing with the 'enhance playlist' feature, and noticed toggling the feature required a reload to show up in the UI. Would be nice to automatically reload Spotify on closing the popup window, but I don't see a way to detect the window closing.
Also the 'Show "Made For You" entry point in the left sidebar' feature seems to be broken, not sure if we can do anything about that.
=> Fixes for expFeatures.js

README.md
Link to installation on website was broken (probably due to splitting it up into simple and advanced installation). Added a link for both simple and advanced installation
=> Fix broken link to installation documentation

Extensions/keyboardShortcut.js
Dribbblish has its own search box, it would be nice if keyboardShortcut.js would select it instead.
=> Select parent element, so dribbblish's custom search box will be selected

install.sh
In theory, fixes #1435.
@ririxidev @theRealPadster
=> fix: replaced file existence check for shell check

src/apply/apply.go
Replaces sideBarItem hook, previously it was appending to the beginning of the file and causing js errors.
=> Fix error with Spotify 1.1.78.765 (Fixes #1449)

CustomApps/lyrics-plus/ProviderMusixmatch.js
Added check to see if track is restricted, returned error if it is to go to next provider.
=> fix: issue where lyrics-plus was stuck on restricted lyrics in Musixmatch

jsHelper/spicetifyWrapper.js
For the now playing song, the properties of the event were a bit changed, so added an exception.
=> fix: issue where new `Spicetify.ContextMenu` items were not added to the now playing song in the bottom.

Extensions/keyboardShortcut.js
I noticed that the keymaps for scrolling stopped working in the current release.
- Spotify version: Spotify for macOS (Apple Silicon) 1.1.79.763.gc2965cdf
- Spicetify version: 2.9.1
The current version of `keyboardShortcut.js` uses the selector `main .os-viewport` (which no longer exists) to focus the main container before scrolling, switching the selector to `.Root__main-view .os-viewport` solved the issue for me.
Using only `.os-viewport` as the selector can be to general since it also matches the sidebar.
=> Changed selector for focusOnApp() in keyboardShortcuts.js

spicetify.go
Updated the text describing the various spictify-cli flags when the `spicetify -h` command is used to reflect the changes made here https://github.com/khanhas/spicetify-cli/pull/1477
This is just my attempt to correct the information displayed in a readable fashion, so please feel free to modify any and all changes I've made here.
=> Updated spicetify -h output with new flag info

install.sh
At 58ee5338dc9ada0b2625113f67e62598bd6bc281, the `install.sh` script fails, exiting with error code `1`.
This is due to this curl:
```bash
command curl -sSf "$latest_release_uri"
```
Now returning:
```json
{
"message": "Moved Permanently",
"url": "https://api.github.com/repositories/159981830/releases/latest",
"documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```
Even if adding `-L` to follow the redirect, the grep will fail since `khanhas` does not match.
This PR fixes that. Copyright notice was left as is.
Just in case it's relevant, and it's a problem on my side, I tested this on my side under:
- OS: Fedora 35
- Curl: 7.79.1
- Bash: 5.1.8(1)-release
=> RFC: Fix install script

CustomApps/new-releases/index.js
(Fix for #1501)
Replaced the selector used to grab the viewport when a user attempts to go to an album listed by the new-releases custom app (Spotify changed/removed some stuff in the last update).
Added the new selector as a property of the Grid class since I thought that would be more appropriate than hardcoding it in both places (and makes it a tiny bit easier the next time Spotify breaks it again and we have to change the selector).
=> fix: `main` selector for newReleases.js

src/apply/apply.go, src/preprocess/preprocess.go
This is a preliminary pull request that will maintain basic support for Spotify 1.1.80 while further hooks are fixed.
- Custom App React symbols
- `Spicetify.React`
- `Spicetify.Platform`
- `Spicetify.ReactComponent.RightClickMenu`
- `Spicetify.ReactComponent.ContextMenu`
- `Spicetify.Menu`
- `Spicetify.ReactComponent.Menu`
- `Spicetify.ReactComponent.MenuItem`
- `Spicetify.ReactComponent.AlbumMenu`
- `Spicetify.ReactComponent.PodcastShowMenu`
- `Spicetify.ReactComponent.ArtistMenu`
- `Spicetify.ReactComponent.PlaylistMenu`
- Home config
It seems `enable-devtool` is no longer functional. I have created a workaround for Windows exectuables. If you install Cheat Engine, attach to Spotify.exe, hit "Add Address Manually", enter `016525fd`, set value to `255`. This will enable devtool when …
=> Fix hooks for Spotify 1.1.80

.github/workflows/build.yml, CustomApps/lyrics-plus/index.js, Extensions/fullAppDisplay.js
As the hermes protocol is broken `1.1.81` onwards, this can "fix" the issue. Now the lyrics-plus background will always match spotify lyrics background.
Maybe, in the future, there is a way to restore the old colorextractor.
=> fix: `fullAppDisplay` album info & background

Extensions/shuffle+.js
`hm://` protocol deprecated, used alternatives to fetch album's and artist's data.
=> updated `shuffle+` to work `1.1.81` onwards

Extensions/fullAppDisplay.js
**Issue:**
If the canvas size of the fullAppDisplay.js is higher then wide the background offset calculation goes wrong and the background is displayed with a gap towards the top.
**Fix**:
This PR changes the calculation to use a different offset in the case of `height > width` which corrects the issue and leads to an expected result.
**Comparison:**
<p float="middle">
</p>
=> fix(fullAppDisplay): background for full screen display on a vertical monitor

install.sh
Fixes:
- fix: doesn't print "spicetify v2.9.4 was installed successfully" when specifying a version anymore.
- fix: doesn't request the latest version when specifying a version anymore.
- fix: allows to input both x.y.z and vx.y.z (for example: 2.9.2 and v2.9.2)
- fix: renamed "shortcut" variable to "releases_uri" for better clarification.
Changes:
- Now prints "FETCHING Version x.y.z" instead of "FETCHING Latest Version" when fetching the latest version.
I did this on purpose, in the end it doesn't really matter, but I guess this is an improvement! 🤷‍♂️
> Note: Hope I did the pull request correctly. I've never made a pull request for code that's still not in the main branch.
@FlafyDev I wasn't sure what was going to happen truly, but now we know that it automatically closes the PR, and I …
=> chore: enhance specific version fetch

CustomApps/new-releases/Settings.js, CustomApps/new-releases/index.js
- Reverting previous changes to "old" solution with new `wg://` protocol
- Leaving notifications and debug logs as they don't change anything
=> fix(new-releases): switch to `wg://` protocol

CustomApps/lyrics-plus/Providers.js, Extensions/popupLyrics.js
* fix: change protocol to wg://
* Fixes issues with getting spotify lyrics on lyrics-plus & popupLyrics
* Adds @ts-nocheck on popupLyrics
* style: change wording when no lyrics
Fixes #1566
=> fix(lyrics): switch to `wg://` protocol

css-map.json
Updated for Spotify: v1.1.83.956
Are their any plans for a more global css map update?
AFAIK, some of the devs here have tools to make it easy to map naming changes
=> Update css-map.json with latest main-trackInfo-*

src/cmd/devtools.go
I forgot to make checking if snapSpotifyHome exists and then overwrite homePath.
=> fix(devtools): overwrite homePath if snap detected

src/cmd/restart.go
Small QoL change, resolves #1469 
Spicetify should check whether process is running and would not launch it if it isn't
Tested and working for Windows
If `pgrep` output is accurately stated [here](https://linuxize.com/post/pgrep-command-in-linux/):
> The command returns 0 when at least one running process matches the requested name. Otherwise, the exit code is 1. This can be useful when writing shell scripts.
Then the result should be the same for Linux/MacOS
=> feat(restart): check if process is running

CustomApps/lyrics-plus/ProviderGenius.js
Add null check for Lyrics Plus since Regex returns unexpected matches (for that I apologize for my carelessness)
<details>
<summary>Tested and working as expected</summary>
- Before:
- After:
</details>
=> fix(lyrics-plus): add null check

CustomApps/lyrics-plus/index.js
This is just more reliable and fetches the color regardless of, if the lyrics are present, unlike the old "fix".
=> fix(lyrics-plus): switch to `wg://` protocol for colors

CustomApps/reddit/index.js, Extensions/bookmark.js, Extensions/shuffle+.js
For `shuffle+`:
The new requests are just more reliable as compared to the `api-partner.spotify.com` requests.
The `fetchAlbum` one is just for sake of consistency.
=> fix: adapt urls in custom app & extensions to `wg://` protocol

jsHelper/sidebarConfig.js
Spotify 1.1.84 changed a lot of classnames, including the ones used in the sidebar config querySelectors. Funnily enough, the old version still worked on macOs. It did however break on Windows and possibly Linux.
Changes have been tested on macOs and Windows.
Fixes #1629
=> fix(sidebar-config): get elements by classname

css-map.json
Fixes #1753
and adds two more missing classes (forward & repeat)
=> fix(css-map): add missing classes for 1.1.87

css-map.json
New class `main-rootlist-rootlistItemOverlay`, was added around .85 - .88
=> fix(css-map): update `1.1.90` classes

CustomApps/lyrics-plus/OptionsMenu.js, CustomApps/lyrics-plus/style.css, CustomApps/reddit/OptionsMenu.js, CustomApps/reddit/style.css
Resolves #1837 
<details>
<summary>Reason behind dumping <code>Spicetify.ReactComponent.MenuItem</code> & findings</summary>
Spotify has hard-locked `MenuItem` usage for artists and profiles only (as seen through `O().isArtist(e)` and `O().isProfile(e)`), both of these boolean values return `false` which explains why Spotify refuses to render dropdown list items:
When trying to force render those items, a bunch of gibberish items are present instead, those of which are only present when right-clicking artist and profile links:
None of those buttons actually leads to the option props passed and thus far I have not found a way of manipulating these items hence why a generic `li` element was used instead
</details>
=> fix(CustomApps): dropdown items not present

CustomApps/lyrics-plus/Pages.js, CustomApps/lyrics-plus/style.css
Resolves #1846
Apparently the ability to seek to lyrics was already available but required the user to double-click (which will highlight some of the texts) and had the default `text` cursor so it was probably not the most intuitive way to let users know such features existed.
=> feat(LyricsPlus): seek to lyrics on click

globals.d.ts, jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Resolves #1849 
I could not find any other way Spotify had used this for their components so this will be an alternative.
Should provide compatibility for custom apps/extensions using `main-type` prefixed classnames also
=> feat(wrapper): add `getFontStyle` method

jsHelper/expFeatures.js, src/apply/apply.go
Resolves #1485 (for real)
Tested and working for both Spotify `1.1.90` and `1.1.91`
<details>
<summary>Technical stuff</summary>
Since `RemoteConfigResolver` is no longer available from `1.1.78`, raw data is fetched from `vendor~xpui` and modified in there instead, using only one method to fetch and override instead of two like before.
Also because there is only one method to fetch these features, there is no effective way to cross-reference and see if old experimental features are still available in newer versions, thus why a `Reset` button is added.
</details>
=> feat: reimplement `Experimental Features`

jsHelper/expFeatures.js
~~Everything is done, for real this time~~
Resolves several inconveniences mentioned in #1865 such as:
~~- Feature list will now automatically updates upon Spotify version mismatch (the `Reset` button stays tho, just in case)
Will now have a notice on the top that tells users to reload for the new changes to apply.~~
Apparently I don't even need this anymore, it just purge the old ones now.
- List will not be shown if hooks are not patched/hasn't loaded yet, which will remove the need for the placeholder text I added before (again, it will stay in case it *does* break again, at least we will know what broke it)
https://github.com/spicetify/spicetify-cli/blob/cf1598dd66d3a27875e01c67369f742d291bc8d3/jsHelper/expFeatures.js#L189
=> feat(expFeatures): update new features upon mismatch

CustomApps/lyrics-plus/Pages.js, CustomApps/lyrics-plus/style.css
- Resolves #1868 (in a different way than suggested)
Saves lyrics upon right-click in a `.lrc` text format
- Hover stuff
=> feat(lyrics-plus): copy lyrics on right-click & stylings

Extensions/shuffle+.js
Resolves #1871 
Conflict caused because `.clearQueue()` is an asynchronous method.
=> fix(shuffle+): fail to put track to queue

CustomApps/lyrics-plus/OptionsMenu.js, CustomApps/lyrics-plus/style.css, CustomApps/reddit/OptionsMenu.js, CustomApps/reddit/style.css, css-map.json, src/preprocess/preprocess.go
Apparently `MenuItem` was not hard-locked, just that it was hooked to the wrong component.
This should return its original functionality for extensions and custom apps' usage (tested with previous commit of Reddit and Lyrics Plus)
Works on as far back as `1.1.88` (haven't tested below)
Also revert custom `MenuItem` commit for both of them and use Spotify's component.
=> fix(preprocess): patch correct component for `MenuItem`

src/utils/config.go
Check AppX path before applying to `config-xpui` to prevent cases like #1810 (way too often) and allow for a second `prefs_path` check in subsequent launches instead of throwing path errors.
Should display a more descriptive error also.
https://github.com/spicetify/spicetify-cli/blob/aacda02ad322adc1d6ac69eb35e715f844c01bdd/src/utils/config.go#L193
=> fix(config): check AppX path before apply to `config-xpui`

src/preprocess/preprocess.go
Apparently there is a special ReactDOM structure used within Spotify that doesn't match RegExp, where `createPortal` is not assigned through conventional means.
Fix aims to use this as a fallback if the original RegExp doesn't match.
[Conversation proving the changes working, along with screenshots of the new section added](https://discord.com/channels/842219447716151306/842818627164962828/1009666775459299338)
=> fix(preprocess): special `ReactDOM` case

Extensions/popupLyrics.js
Hi, here is my first PR, which adds an option to the Popup Lyrics settings menu to set a global delay.
I implemented this because when I'm listening to music with my Airpods on my iPhone, while working on my computer, there always is a delay between the lyrics and the song, and I have to press pause/resume every time to fix it. With this new option, it is now possible to avoid this problem.
By default, delay is set to 0. I made the choice to use an `input type="number"` because a slider / a select / two minus and plus buttons, were not convenient to select a precise value.
=> feat(popup-lyrics): add global delay option

src/preprocess/preprocess.go
~~I'm not sure if anybody uses this, but since it was a function it's better to restore it ig~~
Fixes right-clicking cards in `new-releases` and `reddit`
https://github.com/spicetify/spicetify-cli/blob/253da830d365760a59a5e3c9ad7e8f9a196d2460/CustomApps/reddit/Card.js#L9-L25
Works on as far back as `1.1.90` (haven't tested below)
=> fix(preprocess): menu hooks

src/preprocess/preprocess.go
Should be working again. Network tab no longer reports Sentry requests.
=> fix(preprocess): update `disableSentry` hook

jsHelper/spicetifyWrapper.js
Resolves #1891 
Spotify doesn't bind their function to `_queue` so it will break when reassigned to another property/object
=> fix(wrapper): `Queue` binds

src/apply/apply.go, src/cmd/apply.go, src/cmd/config.go, src/preprocess/preprocess.go
- Extension/Custom Apps developers now have an easier way to check for dependencies and ensure that their script is working with the intended bundle by porting some of the `config-xpui` values to `Spicetify.Config` (Resolves #1920)
- `spicetify config` now prints out Spicetify/Spotify versions also which helps speed up support process for Helpers, and also improve readability for array-like strings by merging them into one line
- New color values for `preprocess` fixing button colors on `active` and `focus`
=> feat: general QoL changes

Extensions/shuffle+.js
Some users find it annoying that the option displays at all times and imo rightfully so when they don't have the intention of using the option on anywhere else other than `Liked Songs` page.
=> fix(shuffle-plus): display liked songs option on relevant page

css-map.json
- Most are new classes never seen before in accordance with the new UI changes.
- `main-topBar-container` is now changed to `main-topBar-contentContainer` due to conflicting CSS rules in xpui between both new and legacy topBar.
- `collection-searchBar-searchBar` is now changed to `main-topBar-searchBar` due to the search bar is now a permanent part of `topBar` and has (somewhat) different styling.
Should fix problems with `Spicetify.Topbar` also with these mappings:
=> fix(css-map): update new layout classes

jsHelper/spicetifyWrapper.js, src/apply/apply.go, src/preprocess/preprocess.go
Resolves #1939 (I hope)
Fix custom apps hook on Spotify version `1.1.95`
Backwards compatible & tested.
=> fix: compatibility with `1.1.95`

globals.d.ts, jsHelper/spicetifyWrapper.js
Some additional toys for devs.
Users and devs can now easily change their keybinds for internal Spotify functions and extensions to their preference without having to modify the extension themselves (not really an option before with default Spotify shortcuts)
=> feat(wrapper): add function to change key bindings

spicetify.go
Would make troubleshooting for the average user a lot easier
=> feat: allow running `config-dir` without valid path

src/cmd/apply.go, src/cmd/backup.go, src/cmd/cmd.go
- Reset path if `prefs_path` is of AppX and invalid (which is the majority case if `prefs_path` issue on Windows), hopefully this solves a handful of issues like this (if not all). This should also ease up the switching process from AppX to normal version after the user reads the message mentioned below:
Also found out that the AppX `spotify_path` may still exist after an uninstallation, so added an extra check to be sure.
- Shows MS Store version warn message on backup along with the `Spicetify not apply on restart` solution and forces the user to respond (and hopefully read) before continuing:
=> fix: clear path if invalid AppX path is used

jsHelper/expFeatures.js, src/apply/apply.go
Works on `1.1.92` and later.
`expFeatures` now override active properties and apply changes in real-time instead of just replacing the default value locally. This also means that **remotely enabled/disabled features** can now be overwritten, and the client no longer needs to reload every time the modal is closed:
Add search modal:
=> feat(expFeatures): general overhaul

globals.d.ts, src/preprocess/preprocess.go
Works from `1.1.90` to latest, has not tested below.
Add `TooltipWrapper` hook for `ReactComponent` for extensions/custom apps. Displays a tooltip while hovering/focusing on an element. Useful for accessibility and UX improvements.
=> feat: add `TooltipWrapper` React Component

css-map.json
Class names concluded after inspecting `xpui.js` and `xpui.css`.
=> fix(css-map): update `navAlt` classes

globals.d.ts
They are given a default value in spicetifyWrapper.js (see below), so should be optional in the ts types.
https://github.com/spicetify/spicetify-cli/blob/c7d4cffbd3beb5b115980c573c4b274cb77e8dc9/jsHelper/spicetifyWrapper.js#L64
Otherwise my ts code complains about `Expected 3 arguments, but got 1.ts(2554)`, but I have no idea what values I should be putting in there, and the code still works without, because of the defaults.
=> fix(types): optional param declaration for `playUri`

install.sh
For install.sh, this will create a blank shellrc file if it doesn't exist. This should fix it so that the install succeeds when the user has no shellrc file. 
As a side note, `$SHELL` doesn't work in Fish. It returns `/bin/zsh` on macOS when running Fish.
=> fix(install.sh): create shellrc file when not found

src/apply/apply.go
Thanks @xerta555 for pointing it out
Remove excess symbol on empty color scheme
=> fix: excess symbol on empty color scheme

CustomApps/lyrics-plus/index.js, CustomApps/reddit/index.js, jsHelper/expFeatures.js, src/preprocess/preprocess.go
- Compatibility with/hotfix for Spotify `1.1.97`
- Fixes issue where launching FAD with Lyrics Plus enabled while on home page crashes the client on the aforementioned version.
Backwards compatible & tested.
=> fix: add support for `1.1.97`

.github/workflows/lintpr.yml, .github/workflows/prettier.yml
This pull request targets fixing Prettier Action cloning branches outside our repo (forks) and to lint `lintpr.yml` file
=> fix(action/prettier): cloning branch in fork

src/apply/apply.go
=> fix: add support for `1.1.99`

jsHelper/spicetifyWrapper.js
Spotify deprecated `isActive` on `1.2.1`, thus active class name is not appended when visiting respective custom apps but shows up only when `Your Library` is active.
The prop is still kept for backwards compatibility
=> fix(wrapper): append active class on custom app location

spicetify.go
(docs) Add macOS instructions for enable-devtools
=> docs(devtools): add macOS instructions

.gitignore, install.ps1, install.sh
A user in the Discord server was having issues with the installer not automatically setting up their shell's PATH to the Spicetify command line executable. I proposed to @theRealPadster that we should start logging installs so if this does happen again, we can review the logs and determine where the problem resides.
This feature:
- Implements a log function in the installer script that continues to log to the standard output as normal, but also logs to a `install.log` file. Each log in the `install.log` file includes a timestamp for convenience.
- Resets the `install.log` file each time the installer script is ran. In hindsight, this could probably be removed if this script gets ran each time Spicetify is updated (via AUR, or whatever package manager/method). We can retain a log of this …
=> feat(installer): write log to file for support

.gitignore
(gitignore) ignore spicetify-cli executable
Summary: Ignore the `spicetify-cli` executable generated from `go build` on Unix
Test Plan: N/A
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/spicetify/spicetify-cli/pull/2085).
* __->__ #2085
=> chore: ignore spicetify binaries

CustomApps/lyrics-plus/README.md, CustomApps/lyrics-plus/index.js
The word "Hiragana" was misspelled in some source code.
=> fix(lyrics-plus): spelling mistakes

globals.d.ts, src/preprocess/preprocess.go
Add `ReactComponent` hooks for text and icon element, works on `1.1.95` and above
Useful in cases where we need to clone Spotify's styling and these element classes aren't mappable
=> feat: add `Text` and `Icon` hooks

jsHelper/sidebarConfig.js
Resize after closing sidebar config to its user specified size
Before:
https://user-images.githubusercontent.com/75513645/213998856-74910f72-075e-4f1c-b874-10e0f761402b.mp4
After:
https://user-images.githubusercontent.com/75513645/213998889-928904a5-fb4c-49c6-a8a2-54e970bf77cf.mp4
=> fix(sidebarConfig): resize after closing sidebar config

CustomApps/new-releases/Card.js, Extensions/bookmark.js, Extensions/shuffle+.js, jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Compatibility patch for Spotify `1.2.4` (im tired)
Listed changes/breaks & fixes:
- Spotify removed the `URI` method and broke it down to several small components/hooks. This patch aims to inject frequently used methods of the `URI` class and creates a backwards-compatible method for extensions/custom apps.
- Added `ReactComponent` to the list of properties to test using `Spicetify.test` for ease of debugging
- Fixed hooks for sub menu components
Works on `1.1.90` and higher, have not tested below.
=> fix: patch for `1.2.4`

CustomApps/lyrics-plus/OptionsMenu.js, CustomApps/lyrics-plus/Translator.js, CustomApps/lyrics-plus/style.css
Changes:
1. Injects the Translator lib when translate option is enabled
2. injects the lib only once
3. fixed menu condition from `!isJapanese` to `isJapanese`
=> fix(lyrics-plus): inject Translator lib when translate option is enabled

.github/dependabot.yml, .github/workflows/build.yml
- See #708 
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
**Before merging this:**
1. Ensure `SPICETIFY_GITHUB_TOKEN` has the `public_repo` scope.
2. Fork https://github.com/microsoft/winget-pkgs under @spicetify. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.
You can test out the action inputs in this [playground](https://bittu.eu.org/docs/wr-playground).
If you want to see an example …
=> ci(github/workflows): add Winget Releaser

Extensions/webnowplaying.js
In the WebNowPlaying browser extension, they just concatenate 'PLAYER:' with the name of the player. So they do 'ws.send("PLAYER:" + currPlayer);'. Therefore, youtube.com returns '`Youtube`' to my measure in rainmeter, but spicetify returns:
'` Spotify Desktop`'.
=> fix(webnowplaying): remove extra space in ws message

Extensions/shuffle+.js, globals.d.ts
As title suggests:
Also updates type declaration for the `URI.Type` object.
=> feat(shuffle+): add `Local Files` shuffling

.github/workflows/build.yml
This token should only be used for this as it only has the `public_repo` scope.
=> fix(workflows/winget): use new token

CustomApps/lyrics-plus/OptionsMenu.js, CustomApps/lyrics-plus/style.css, CustomApps/reddit/OptionsMenu.js, globals.d.ts, src/preprocess/preprocess.go
Also solves an issue with Lyrics Plus unavailable message on small width
Resolves #2003
=> fix: patch for `1.2.8`

globals.d.ts, src/preprocess/preprocess.go
Resolves #2177 
Exposes new URI class & update types
Tested on `1.2.4` to latest, which is the oldest version where the class was updated.
=> fix(preprocess): expose URI class & update types

CustomApps/lyrics-plus/index.js
Lyrics have been severely slow to load since the Japanese & Chinese text conversion option patch. Of course, if you disable the conversion option, it loads quickly, but I think you'd better disable the default value of the conversion option for those who don't listen to that music.
=> perf(lyrics-plus): disable conversion by default

jsHelper/homeConfig.js, src/apply/apply.go
~~This thing has been broken for so long people forgot it existed lol~~
Works on `1.1.90` and higher, broken on `1.1.85` (as in the regex matched but they weren't using `home-v2`), have not tested in between.
`useEffect` implementation for menu item was removed because in some specific versions the `useEffect` hook was not present in the file.
=> fix(home-config): patch for v2

Extensions/popupLyrics.js
This is a bug that's been around for a long time. Providers in popupLyrics failed to switch normally. For example, if you get an error while looking for the lyrics for musixmatch, even if netase was enabled, the transition was not possible. Additionally, the desc of the providers has been modified to be the same as lyrics-plus.
=> fix(popupLyrics): providers change fix

globals.d.ts, jsHelper/spicetifyWrapper.js
A lot of extensions seem to rely on adding icons to player controls yet we don't have any conventional method of doing it (surprisingly after years) so here we are
=> feat: add playbar button method

Extensions/webnowplaying.js
- Fixed a memory leak that occurs when the extension fails to connect for ~256 times.
Chromium has a global websocket connection limit of 256 and it just goes crazy when it hits that, this was caused because I wasn't closing the websocket properly before trying to reconnect.
- Fixed WebNowPlaying being unable to heart/unheart a song
- Fixed some issues with caching
=> fix(webnowplaying): memory leak

spicetify.go, src/cmd/upgrade.go, src/utils/scanner.go
Although this solution partially resolves #2071, we do not intend to implement a fully-fledged auto-update feature due to the potential risk of Spotify causing disruption to Spicetify's functionality at any point. As a result, our solution involves utilizing the `--check-update` flag, which can be added to any command. This allows users to create a shortcut that can update Spicetify prior to launching Spotify
=> feat: add check-update flag

globals.d.ts, jsHelper/spicetifyWrapper.js
In a very grim scenario this could happen
In order to not discourage extension devs from registering an icon in cases like so, and since the player is a stateful component, it makes sense to add the ability to hide/show the button when needed.
=> feat(wrapper): add method to hide/show player button

jsHelper/spicetifyWrapper.js
This has been broken for a lot of versions now.
Basically the event never fired before because the element child was the one that had changing children.
=> fix(player): listen to child on `appchange`

CustomApps/lyrics-plus/ProviderMusixmatch.js
Dude prob didn't test it after refactoring.
Basically they multiplied every time variable by 1000 expect for this one, so most of them returned a negative value.
=> fix(lyrics-plus): parse Musixmatch karaoke time

spicetify.go, src/apply/apply.go, src/cmd/apply.go, src/cmd/cmd.go, src/cmd/path.go, src/cmd/watch.go, src/utils/config.go
This removes the need for every theme to have its own install script in which it needs to move js files and modify the config, this PR will not affect older themes that do not have a theme.js.
As a side improvement i have modified the `spicetify path` command to be more consistent with additional missing options such as root paths for; themes, extensions, and customapps. 
##
=> feat: add support for theme's script

jsHelper/spicetifyWrapper.js, src/cmd/apply.go
This is aimed to prevent at much user error as possible created by using an outdated version of Spicetify ~~because I'm honestly really tired at the amount of thickets and spam issues lol~~.
- Creates an in-app update notification that appears on the Topbar
- Discourage running `apply` on outdated preprocess data
=> feat: notify update in-app

spicetify.go
I remove watch command's description "On default, update CSS on color.ini or user.css's changes." because `spicetify watch` without any flags doesnt watch the theme
=> docs: update help

spicetify.go
Spicetify v2.17.1 prints the following with no commands:
```
$ spicetify
info Run "spicetify -h" for commands list.
```
It might as well just print the help text that it suggests to the user.
=> feat: help on no commands

CustomApps/reddit/index.js
`URI.fromString` throws an error on invalid URI, while `URI.from` returns null. Might have been an oversight from my previous patch.
=> fix(reddit): ignore on invalid URI

CustomApps/lyrics-plus/OptionsMenu.js, CustomApps/lyrics-plus/Pages.js, CustomApps/lyrics-plus/Settings.js, CustomApps/lyrics-plus/index.js
This PR resolves #1765, adds a global delay option in lyrics-plus settings.
This global delay is added onto the track delay (previously named just 'delay').
=> feat(lyrics-plus): global delay

src/cmd/config.go
Currently the arraytype function that handles extensions and custom_apps lets you pass a flag like so to remove its entry from the config: `spicetify config extensions extension.js-`
This PR adds this functionality to stringtype function which includes: "prefs_path", "spotify_path", "current_theme",  and "color_scheme".
=> feat(config): string type value remove flag

css-map.json, globals.d.ts, jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Hooks a new component to display a confirmation dialog as a popup modal. Works on `1.1.97` and above, have not tested below.
=> feat(react-component): add `ConfirmDialog`

globals.d.ts, jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Hooks onto Spotify's GraphQL handler and definitions. This allows developers to make queries to Spotify GraphQL endpoints easily without having to use obscure hashes for persisted query validation.
Works on `1.1.90` and above, have not tested below.
This also includes all possible definitions for accepted queries
These definitions can be passed to the `Request` method as the first parameter for each query you want to fetch.
Additionally, since these are GraphQL definitions, they also include parameter type definitions so developers can easily catch on and utilize it.
=> feat: hook GraphQL wrapper

CustomApps/lyrics-plus/ProviderNetease.js, Extensions/popupLyrics.js
1. The existing Netease lyrics were too inaccurate. In addition to comparing album names, this commit adds a method of comparing the length of the song in milliseconds (milliseconds are specified as ±500 milliseconds because there is a slight error), if either of these conditions is not met, it returns no lyrics (because otherwise useless lyrics will be returned)
2. The return value "纯音乐, 请欣赏" for lyrics Netease doesn't seem to be the track Instrumental. Sometimes when listening to local music or songs by indie artists, Instrumental is displayed. Therefore, it was modified to be displayed as no lyrics.
3. Fixed an issue where, when viewing the lyrics of Netease" in popupLyrics, the song would be displayed as prelude if there was a blank during the lyrics. the problem did not exist in …
=> feat(lyrics-plus): improve Netease lyrics algorithm

jsHelper/sidebarConfig.js
Account for the fact that the Create Playlist item is pre-arranged even before it is rendered(?)
And wait for the rootlist in Library X to finish rendering when switching between 2 styles.
=> fix(sidebar-config): dynamic apply between UI

CustomApps/lyrics-plus/PlaybarButton.js, CustomApps/lyrics-plus/Settings.js, CustomApps/lyrics-plus/index.js, CustomApps/lyrics-plus/manifest.json
=> feat(lyrics-plus): playbar button

CustomApps/lyrics-plus/ProviderNetease.js, CustomApps/lyrics-plus/Utils.js, Extensions/popupLyrics.js
In addition to `feat` and `with`, we modified the regular expression to detect `prod`, which means the producer of music.
Additionally, when empty lyrics are delivered in popupLyrics, there is an empty array, and the empty lyrics are printed out, so we modified it to print out that there are no lyrics.
=> feat: modify lyrics cleantitle regex & netease lyrics update

CustomApps/new-releases/Card.js, CustomApps/new-releases/Settings.js, CustomApps/new-releases/index.js, CustomApps/new-releases/style.css
Adds a close button to the top right of cards, once clicked a function is ran that adds the releases uri to an array which is then used by refresh() to refresh the grid whilst skipping those specific uris, aims to resolve #2317.
example video:
https://cdn.discordapp.com/attachments/842219447716151310/1104487178702180423/screen-capture.webm
=> feat(new-releases): dismissible cards

Extensions/fullAppDisplay.js
Previously, only albums released in recent 6 months show the exact day, now all albums show their exact release day regardless the album is new or not.
=> feat(fullAppDisplay): show always the exact releaseDate

Extensions/fullAppDisplay.js
- Previously, releaseDate is appended to the album name by `albumText += " • " + (await this.getAlbumDate(albumURI));`. Sometimes if the album name is a little bit longer, some part of the releaseDate string will be pushed to the next line, mostly it's the year, but sometimes even the month or the whole releaseDate string), which does not look good. 
- Now, everything matches the rest, just added an option to toggle releaseDate on and off🥳🥳🥳!
=> feat(fullAppDisplay): add option to display release date

CustomApps/new-releases/Card.js, CustomApps/new-releases/index.js, CustomApps/new-releases/style.css
Comparison of the new border radius of new-releases card (blue), and default spotify card (red).
Since we are unable to receive any of the crucial variables that the radius relies on, i have taken advantage of the fact clamp will default to 0px when --column width isnt present, and since this variable isnt relied on anywhere else there is no need for it and will default to 0px in the clamp as spotify intends.
This is a pretty janky solution to come to, but it was either that or modify the --card-container-border-radius mentioned above for a multitude of classes.
this leaves us looking like this:
=> style(new-releases): match spotify card styling

CustomApps/new-releases/Card.js, globals.d.ts, jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Introduce the `ReactHook` method and `DragHandler` hook, helps integrates Spotify components created by extensions and custom apps.
Works on `1.2.6` and later, breaks on `1.1.96`, have not tested in between.
https://github.com/spicetify/spicetify-cli/assets/77577746/dab0633a-6d27-4208-a836-d92070c1a2f8
https://github.com/spicetify/spicetify-cli/assets/77577746/c3e462e2-0639-48c9-951b-fddb2cf0823d
This will hopefully lay a foundation if we were ever to expose React hooks
=> feat(react-hook): add method & `DragHandler`

globals.d.ts
URIs can have track and duration properties for local tracks, which are undocumented. For example,
```js
Spicetify.URI.from("spotify:local:Andrew+Hale+%26+Simon+Hale:L.A.+Noire:Global+Chase+Full:129")
```
returns 
```js
{
"type": "local",
"artist": "Andrew Hale & Simon Hale",
"album": "L.A. Noire",
"track": "Global Chase Full",
"duration": 129
}
```
=> chore(types): update local URI properties

jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Spotify uses a duplicate function to compare Episode URI for whatever reason.
=> fix(URI): hook onto base component

Extensions/trashbin.js
The trashbin extension is currently broken, since `isBanned` isn't defined, which is the variable which determines whether the current track should be skipped.
This PR additionally invokes `watchChange` when the event listeners are activated. By doing so, we can handle tracks that are already playing upon the initial loading of the extension, as well as tracks that are playing when the extension has just been enabled through the settings page.
=> feat(trashbin): fix code & handle player state upon enable

jsHelper/spicetifyWrapper.js
The code below didnt used to work, this will fix it.
```js
const element = document.querySelector("#Custom-Image-URL > div.col.action > input")
const tooltip = Spicetify.Tippy(element, {
...Spicetify.TippyProps,
content: `
<div>
<h6>People</h6>
<ul>
<li>People Feature 1</li>
<li>People Feature 2</li>
<li>People Feature 3</li>
</ul>
</div>`,
allowHTML: true
}
```
=> fix(tippyProps): allow innerHTML property

src/preprocess/preprocess.go
For some reason on this specific version, Spotify decided to be lazy and not write an additional case for `NowPlayingView` like they have done for every other panel like before.
Since React Components cannot return `undefined` we can be sure there will always be something on the other end of the null coalescer.
=> fix(panel): render `NowPlayingView` on `1.2.9`

jsHelper/spicetifyWrapper.js
Using override values allows us to more accurately "reset" the product state values since we are not having to rely on a variable declared once at startup.
Example where this is needed:
- await Spicetify.AppTitle.set("test")
- restart Spotify
- await Spicetify.AppTitle.reset()
- await Spicetify.AppTitle.get()
> returns "test"
Provided you havent hit the re-occurring time limit for Spotify to reset the name, the temporary variable is assigned to the previously set value at startup, this makes it difficult for developers to predict the true value of the title.
Using override values completely separates our changes from the true values of the product state.
=> fix(wrapper/app-title): use override values

src/cmd/watch.go
For example `spicetify watch -[insert optional flag(s) here]` will watch for changes and restart as expected but with the devtools enabled so a separate command is not needed to enable devtools. This is useful for debugging and development.
Works just fine, though as far as I can tell this is certainly not the most efficient way to do this, so someone with a better understanding of the codebase should probably take a look at this.
=> feat(watch): enable devtools

jsHelper/spicetifyWrapper.js
Spotify does not have error boundaries for their right sidebar, so when the Panel component throws an error, the whole client crashes, and will continue to crash in subsequent reloads if the panel ID is cached into state as the client attempts to open last closed panel.
This is made to prevent the client crashing and logs an error stack in addition to React's usual error code.
=> fix(panel): catch error & prevent crashing client

globals.d.ts, jsHelper/spicetifyWrapper.js
Pass panel ID as props since the Panel header requires the panel ID to be passed (doesn't seem to be optional internally, but still works fine without?), plus for more usage inside the panel component as the ID is not accessible until after the panel is registered.
Works fine with both types of children.
=> feat(panel): pass panel ID as props

globals.d.ts, jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Expose the `ReactFlipToolkit` module used by Spotify.
https://github.com/aholachek/react-flip-toolkit
tl;dr: This method works on as far back as `1.2.2`, have not tested below:
Because the module isn't imported until required (in this case the Buddy Feed panel uses it), the module won't be initialized. To circumvent this, we need a function that will force load all available Webpack modules. Note that this **will not** load modules outisde of imported Webpack chunk, meaning modules in `xpui` and `vendor~xpui` will always be loaded and there will be no significant performance impact.
The naming convention for the method also doesn't change between versions as this method was discovered in April. This will also help in hooking components in the future, and we could also leverage this for …
=> feat: expose `ReactFlipToolkit` & `classnames`

.github/CODEOWNERS
This damn thing forces me to subscribe to EVERY single PR posted to the repo. I do not want to be requested to review every single PR. I will review PRs if I want. Forcing every CLI member to receive notifications about every PR in the entire repo is super spammy.
=> chore(github): Remove CODEOWNERS

Extensions/fullAppDisplay.js
=> fix(fad): lyrics plus positioning

css-map.json, globals.d.ts, jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Not much to say except moving to Webpack hooking for `DragHandler` instead of maintaining 2 dreadful hooks
Cool stuff also
=> feat(wrapper): expose `ReactQuery` & `usePanelState`

src/cmd/upgrade.go
This PR will ensure the user is told the correct commands to run, the issue this solves is:
whenever a users Spotify has updated BEFORE they then run `spicetify upgrade`, the backups are mismatched, they are then told to run `spicetify restore backup apply` which will plonk their old backup files into their new spotify installation causing issues. This PR checks for this and tells them to just run `spicetify backup apply`.
=> feat(upgrade): verify backup status

CustomApps/lyrics-plus/style.css
Not much more to say other than the title, prevents the changes lyrics-plus makes to typical Spotify divs such as .col from affecting the entire dom by limiting the selectors to our own containers.
=> style(lyrics-plus): restrict selectors to app

jsHelper/sidebarConfig.js
Retain ID when sidebar re-renders on changing mode, expanding.
=> fix(sidebar-config): retain `id` on re-render

css-map.json
This would fix misaligned buddy feed header
Before version 1.2.0 buddy feed header has class `PJt6DU4NhGjz7fVCZjS7` and its styles were stored in `xpui-routes-buddy-feed.css`, but starting with version 1.2.0 the class name has changed and its styles moved to `xpui.css`, so the styles in `xpui-routes-buddy-feed.css` became obsolete and weren't apply anymore. Spicetify changes both the actual class name in `xpui.css` and the obsolete ones in `xpui-routes-buddy-feed.css` to `main-buddyFeed-header`, resulting in incorrect styling and misalignment
stock:
with spicetify applied:
since versions below 1.2.0 aren't supported anymore and in 1.2.0 it is different class name, I think this class can be removed from the map
=> fix(css-map): remove outdated buddy feed header class

jsHelper/spicetifyWrapper.js
Uncaught error caused by one item affects all other items as the loop gets broken and the function never reaches the part where all items are prepended at once. 
https://github.com/spicetify/spicetify-cli/blob/4393d2fb02d435f6e3ea4e0224553c95225d95c7/jsHelper/spicetifyWrapper.js#L1466
=> fix(context-menu): catch error for items

jsHelper/spicetifyWrapper.js
Shows descriptive error message if possible, instead of having users second guessing where the stack is from.
=> feat(panel): descriptive error message

Extensions/keyboardShortcut.js
This PR removes redundant keybinds that Spotify have implemented into their own shortcut menu (ctrl + ?), whilst also fixing pre-existing ones (namely rotate navbar item which broke from libx).
The registering of these binds has also been moved to a json/object structure making it easier to expand upon both on the dev side and in a future settings menu if we were to add one.
Also moved from `Spicetify.Keyboard` to `Spicetify.Mousetrap`
(docs will need rewriting)
=> refactor(keyboardShortcut): cleanup & patch keybinds

CustomApps/lyrics-plus/ProviderNetease.js, CustomApps/lyrics-plus/Utils.js
The old xianqiao.wang API seems like removed; therefore, I switch it to PyNCMd, which is actively maintained.
Besides, in Spotify Taiwan, the album name is in Traditional Chinese, which is not aligned with what NCM chooses. Therefore, I have written a simple converter that converts the Traditional Chinese album name to Simplified Chinese so that we can compare the correct album name in such cases.
Note that:
* The PyNCM I choose is from [UnblockNeteaseMusic/music](https://github.com/UnblockNeteaseMusic/server/blob/62b958d83f91ae7b196b9c52f9da870426665df4/src/provider/pyncmd.js#L7). It has been online for at least 3 weeks.
* The PyNCM instance I used have not supported karaoke lyrics, but [PyNCM indeed support fetching it](https://github.com/mos9527/pyncm/blob/master/pyncm/apis/track.py#L13 …
=> fix(lyrics-plus/netease): use PyNCMd API

globals.d.ts, jsHelper/spicetifyWrapper.js
Exposes the `ButtonPrimary`, `ButtonSecondary` and `ButtonTertiary` react components to make Spotify buttons.
Also adds types for ColorSets, though Spotify's own ColorSets have not been exposed.
```js
var exampleIconComponent = (props) => Spicetify.React.createElement(Spicetify.ReactComponent.IconComponent, {...props, dangerouslySetInnerHTML: {__html:`<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 76.465 68.262"><path d="M151.909 72.923v6.5h10.097l8.663 44.567h48.968v-6.5h-43.61l-1.2-6.172h42.974l10.35-33.91h-59.915l-.872-4.485H151.91zm17.59 10.984h49.867l-6.393 20.91h-39.409l-4.064-20.91zm5.626 44.11a6.5 6.5 0 0 0-6.5 6.5 6.5 6.5 0 0 0 6.5 6.501 6.5 6.5 0 0 0 6.5-6.5 6.5 6.5 0 0 0-6.5-6.5zm38.274 0a6.5 6.5 0 0 0-6.5 6.5 6.5 6.5 0 0 0 6.5 6.501 6.5 6.5 0 0 …
```
=> feat(wrapper): expose `Button` components

.github/workflows/build.yml
Winget Releaser now supports non-Windows runners. Now we can include the step in the `trigger-release` job.
=> ci(github/workflows): merge `trigger-winget-release` job

CustomApps/lyrics-plus/Utils.js
A small nit-pick about #2508, Traditional Chinese is divided to Hong Kong Traditional Chinese and Taiwan Traditional Chinese. Those regional variants of Traditional Chinese uses different characters in some instances, for example: 着 in Hong Kong and 著 in Taiwan. 
When I first implement the function of converting Simplified Chinese to Traditional Chinese and vice versa. It became obvious that some songs uses either Hong Kong Traditional Chinese or Taiwan Traditional Chinese. Figuring out how to differentiate those two Traditional Chinese was hard until I dig into the OpenCC's character convert website. They pretend that those two as OpenCC Traditional Chinese standard (which is specific to OpenCC only) instead of figuring out what is what.
Seeing the commit, I see that in the …
=> fix(lyrics-plus/utils): force usage of OpenCC standard

CustomApps/lyrics-plus/ProviderNetease.js
According to https://github.com/spicetify/spicetify-cli/pull/2516#discussion_r1296116363
=> refactor(lyrics-plus): unneeded interpolation

Extensions/popupLyrics.js
applied PyNCMd API to popupLyrics in the same way as #2508
=> fix(popupLyrics/netease): use PyNCMd API

globals.d.ts, jsHelper/spicetifyWrapper.js
This fixes getting the `Spicetify.Player.data` for `1.2.19` and higher due to `sp://` endpoint being deleted. For compatibility I added the `track` object that was returned by the endpoint
=> fix: use PlayerAPI for `Player.data`

CustomApps/lyrics-plus/ProviderMusixmatch.js
This PR modifies the parameters of Musixmatch API `track.richsync.get` (method to get karaoke lyrics) based on the latest Musixmatch Studio (https://curators.musixmatch.com) implementation.
This will allow you to get word-by-word synchronization data that matches the duration of the song.
=> fix(lyrics-plus): add missing params for mxm richsync

src/cmd/patch.go
required if you need, for example, to patch `vendor~xpui.js`
=> fix(cmd/patch): support `~` in file names

CustomApps/lyrics-plus/PlaybarButton.js, jsHelper/spicetifyWrapper.js
Spotify has started wrapping playbar buttons in a span instead of displaying as block, to prevent weird padding behaviour between ours and their buttons; we should do the same.
before:
after:
=> fix(wrapper): playbar.button match Spotify structure

jsHelper/spicetifyWrapper.js
before:
`encore-dark-theme main-contextMenu-menu` classes are missing
after:
=> fix(wrapper): correct webpack module for `Spicetify.ReactComponent.Menu`

.github/workflows/build.yml
I've fixed the reverse proxy on my server as well as fixed the .SRCINFO issues, so I'm putting it back with the old URL. I did test this and it works.
Partial revert of #2058
=> ci(github/actions): re-enable HTTPS on AUR update request

.github/workflows/build.yml
The bug we found in #2576 has now been fixed in https://github.com/mislav/bump-homebrew-formula-action/releases/tag/v3.1.
=> chore: bump homebrew action

src/cmd/apply.go, src/cmd/backup.go
=> feat(cmd): request to stop the process if backup is outdated

jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
implements Spotify's new (1.2.22.982) notification system resolves #2600
```js
Spicetify.Snackbar.enqueueSnackbar('I am an exception', {
autoHideDuration: 3000,
style: {
backgroundColor: "purple"
},
onClose() {
console.log('closed')
},
variant: 'info',
})
```
```js
Spicetify.Snackbar.enqueueSnackbar(
`<div class="TcJ5lUfQ25AJNoCrWO5Z">
<div class="xaCo5LWfBMxqfWjUA3o2">
</div>  
<div class="r4Hbxvv02KfOVeZ_v335">
<span data-encore-id="type" class="Type__TypeElement-sc-goli3j-0 TypeElement-ballad-textBase-type">
Added to 
<span data-encore-id="type" class="Type__TypeElement-sc-goli3j-0 TypeElement-balladBold-textBase-type">
▸ Tasteful 👌
</span>
</span>
</div>
</div>`,
{ persist: true },
);
```
```js
Spicetify.Snackbar.enqueueSnackbar('barebones snack')
```
```js …
```
=> feat(preprocess): implement snackbar api

Extensions/keyboardShortcut.js
Add an extra query selector to the vim bindings to enable interfacing with the playlist list in the main menu to the left.
=> fix(keyboardShortcut): enable playlist selection

jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Now we can deprecate `showNotification`
=> refactor(wrapper): combine snackbar and notification apis

css-map.json
the new homescreen cards have an equalizer like main-trackList-playingIcon
=> chore(css-map): view-homeShortcutsGrid-playingIcon

jsHelper/spicetifyWrapper.js
Fixes #2621
Since function only waits 10ms for both functions (or one of them) to appear, `vendor~xpui.js` isn't loaded fully and one function is assigned faster than other one
=> fix(wrapper): make the snackbar a priority

jsHelper/spicetifyWrapper.js
This allows the user to not have to rely on enqueueImageSnackbar if they want to say, have the image come after the text instead of before or in the example below add an undo button since that component has no trailing prop.
```js
Spicetify.Snackbar.enqueueCustomSnackbar({
key: "test",
children: Spicetify.ReactComponent.Snackbar.wrapper({
children: Spicetify.ReactComponent.Snackbar.simpleLayout({
leading: Spicetify.ReactComponent.Snackbar.styledImage({
src: "https://i.imgur.com/uPbnZkz.png",
imageHeight: "24px",
imageWidth: "24px"   
}),
center: "song action",
trailing: Spicetify.ReactComponent.Snackbar.ctaText({
ctaText: "undo",
onCtaClick: Spicetify.Snackbar.handleCloseSnack("test"),
}),
}),
}),
});
```
However, this component isnt only used for snacks and as such can also be used like …
=> feat(snackbar): styledImage component

jsHelper/spicetifyWrapper.js
New versions of Spotify do not select the correct function, whilst it would be preferable to use `functionModules.find(m => m.toString().includes("confirm-dialog-description"))` i do not have the patience to check every supported version of spotify to see if that classname is present. This approach should theoretically cover all older versions since kyries original pr showed onclose being passed as a prop.
```js
Spicetify.ReactDOM.render(
Spicetify.ReactComponent.ConfirmDialog({
titleText: "hi",
descriptionText: "hi",
cancelText: "hi",
confirmText: "hi",
confirmLabel: "hi",
}),
document.querySelector(".ReactModalPortal"),
);
```
=> fix(wrapper): confirmdialog component

jsHelper/spicetifyWrapper.js
=> fix(wrapper): wrong icons color

.github/workflows/build.yml, go.mod, jsHelper/spicetifyWrapper.js, spicetify.go, src/apply/apply.go, src/cmd/apply.go, src/cmd/auto.go, src/cmd/cmd.go, src/cmd/update.go, src/cmd/watch.go, src/utils/config.go
Following the discussions on #2528 and on Discord, this PR removes the `--check-update` flag and makes the `upgrade`/`update` semi-chainable. Also renamed the old `update` to `refresh` as it felt that it was the word that made the most sense based on what the function did and the PoV of the user.
=> feat: `update` rework

Extensions/fullAppDisplay.js
Corrected as it was not designed for the case where the music was not selected.
=> fix(fullAppDisplay): return when `Player.data` is null

CustomApps/lyrics-plus/OptionsMenu.js
The removal of root__topbar in later versions of spotify means rendering inline is no longer possible.
=> fix(lyrics-plus): optionsMenu-dropBox tippy

jsHelper/spicetifyWrapper.js
resolves #2646
improves upon #2647
Completed:
- updated check icon
- updated dropdown icon
- added trailingIcon
- ability to override dropdown icon for custom icon
- ability to have both a prepended icon (icon) and appended icon (trailingIcon)
Showcase:
Not a realistic use case for the last image, just to show the ability to override as devs wish.
=> feat(wrapper): menuitem add trailingIcon parameter

jsHelper/spicetifyWrapper.js
It can be used like:
```js
const container = document.createElement("div");
container.id = "spicetify-chip-examples";
container.style.width = '100%';
container.style.padding = '10px';
document.body.appendChild(container);
// JSX
ReactDOM.render(<div>
<Spicetify.ReactComponent.Chip
className="encore-dark-theme"
isUsingKeyboard={false}
onClick={(e: Event) => {
Spicetify.showNotification("Chip clicked!");
}}
>Click me</Spicetify.ReactComponent.Chip>
<Spicetify.ReactComponent.Chip
className="encore-dark-theme my-class"
isUsingKeyboard={false}
size={true}
>I'm resizeable</Spicetify.ReactComponent.Chip>
<Spicetify.ReactComponent.Chip
className="encore-dark-theme"
isUsingKeyboard={false}
iconTrailing={() => (
<Spicetify.ReactComponent.IconComponent
semanticColor="textBase" …
```
=> feat(wrapper): add Chip component

globals.d.ts
Adds missing types for the `ButtonPrimary`, `ButtonSecondary` and `ButtonTertiary` components, and fixes the duplicated `iconTrailing` property.
=> fix(types): add missing types for button components

src/cmd/cmd.go, src/utils/path-utils.go
=> feat: allow for env variables in config paths

jsHelper/spicetifyWrapper.js
#1912 isn't reproducible with spotify v1.2.0, and since spotify v1.2.23 this function calls itself endlessly because of the `.Root__top-bar` element removal
=> fix(wrapper): remove outdated `attachObserver` function

jsHelper/spicetifyWrapper.js
definitely some super-legacy thing, also no one uses it
didn't touch the types because will create a separate pr for them
=> feat(wrapper): remove `appchange` event from player

jsHelper/spicetifyWrapper.js, src/preprocess/preprocess.go
Related to #2707, however, it seems like it's useful in some use cases like using it without framework. well, whatever
resolves #2711
=> revert: enhance snackbar exposition

jsHelper/spicetifyWrapper.js
=> fix(wrapper): add optional chaining to `colorExtractor`

jsHelper/spicetifyWrapper.js
before:
after:
i havent tested on older versions, but it doesnt look like these functions have changed its just that newer functions added to xpui happened to use the same keywords, so likely unnecessary to test
=> fix(wrapper): simpleLayout & wrapper

CustomApps/lyrics-plus/TabBar.js, CustomApps/new-releases/Card.js, CustomApps/reddit/TabBar.js, css-map.json, jsHelper/spicetifyWrapper.js
Adds mapping for `.search-searchBrowse-browseAllWrapper` in Spotify 1.2.26.1187.g36b715a1
=> feat(css-map): update css mapping for search browse-all wrapper

.gitignore, Extensions/shuffle+.js
Fixes #2689
spotify's internal magic breaks on setting context for local files
=> fix(shuffle+): remove context for local tracks

src/cmd/cmd.go, src/utils/config.go
more readable code + no more "i switched to the classic version, but spicetify still says that i have the ms store one"
=> refactor(cmd): rewrite `InitPaths` func

jsHelper/spicetifyWrapper.js
rn if you change the volume and then mute using the spicetify api, when you un-mute by clicking the button, you won't get the previous volume level
in short, the spotify internal variable is out of sync with `_volumeBeforeMute` and there is nothing that can be done about that
=> revert(wrapper): use button clicking for `Player.setMute`

jsHelper/spicetifyWrapper.js
tested with spotify 1.2.26 and 1.2.0
=> feat(wrapper): expose Card React components

.github/workflows/build.yml
This should help avoiding `GLIBC x.x not found` errors on outdated linux distributions
=> fix(build): disable CGO

src/cmd/cmd.go
so that's why the check was there
=> fix(cmd): check for spotify.exe existence instead of app folder

spicetify.go
A small code refactoring.
`len(flags) != 0` is redundant because `range` already skips empty slice.
=> refactor(spicetify): remove redundant `len` check

jsHelper/spicetifyWrapper.js
=> fix(contextmenu/item): return to original `isEnabled` behavior

css-map.json, jsHelper/spicetifyWrapper.js
fixes #2806
explanation: the topbar is only re-rendered in few specific page switches so
=> fix(wrapper/topbar): use `History.listen` event instead of the observer

jsHelper/spicetifyWrapper.js
resolves #2834
this is stupid workaround but 🤷‍♀️
=> fix(wrapper/chunks): add failsafe for `1.2.31`

CustomApps/lyrics-plus/Pages.js, CustomApps/lyrics-plus/ProviderGenius.js, CustomApps/lyrics-plus/ProviderMusixmatch.js, CustomApps/lyrics-plus/ProviderNetease.js, CustomApps/lyrics-plus/TabBar.js, CustomApps/lyrics-plus/index.js
I don't have time, patience and knowledge to bypass cloudflare in a way, that genius would work all the time
=> fix(lyrics-plus): disable genius for `1.2.31` and higher

jsHelper/spicetifyWrapper.js
This fixes #2879 (https://github.com/spicetify/spicetify-cli/commit/c866648e6b40412fd4610a4534a04e945976ef92). Without applying `main-topBar-button` class on the button itself it will create blocky element on the left items
before:
after:
=> fix(wrapper/topbar): apply `main-topBar-button` on button not element

.github/workflows/build.yml
Spicetify has its own formula in `homebrew-core` repo, https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/spicetify-cli.rb, so we don't really need to maintain our own tap for this. Anyone that uses our tap should switch to core tap
thanks to https://github.com/khanhas/homebrew-tap/pull/14, otherwise I wouldn't know that's the case tbh. 
We **should also archive** https://github.com/spicetify/homebrew-tap after merging this pull request
=> ci: remove 'update the homebrew tap' step

src/preprocess/preprocess.go
No more console log hijacking 🎉
=> fix: disable sentry completely

jsHelper/homeConfig.js, jsHelper/sidebarConfig.js, src/apply/apply.go
in reference to [this description](https://github.com/spicetify/spicetify-cli/pull/2888#issue-2177763270)
regex tested on:
=> fix(homeConfig): support all versions

jsHelper/spicetifyWrapper.js
Fixes this for `1.2.33` and higher:
after the fix:
=> fix(styledClassName): add another key and exclude one

CustomApps/lyrics-plus/TabBar.js, CustomApps/new-releases/Card.js, CustomApps/reddit/TabBar.js, biome.json, src/utils/config.go
=> feat(config): add another folder to `potentialList`

css-map.json, jsHelper/spicetifyWrapper.js, src/apply/apply.go, src/preprocess/preprocess.go
This pull request:
- adds topbar buttons on the left back
- adds scrollable container on navlinks so they don't overflow with other ui elements
- maps css
- adds polyfill for `1.2.13` -> `1.2.23` (chromium <117) for `Object.groupBy`
- adds old `classnames` regex back for `1.2.13`
- fixes adding jsHelpers to body tag in `1.2.34`
=> fix: make various changes to global navbar

CustomApps/lyrics-plus/TabBar.js, CustomApps/reddit/TabBar.js, CustomApps/reddit/index.js, jsHelper/spicetifyWrapper.js, src/apply/apply.go
=> feat: add support for pre-Library X UI again

jsHelper/spicetifyWrapper.js, src/apply/apply.go
To be honest, I forgot about `SeekToCloseParen` lol
=> feat(navlink): match spotify style & use `SeekToCloseParen`

.github/workflows/build.yml
i don't kinda understand why we don't support windows arm64. Spotify supports it, so why won't we?
=> ci(release): add support for windows `arm64`

src/preprocess/preprocess.go
Fixes https://github.com/JulienMaille/spicetify-dynamic-theme/issues/68
=> fix: do not replace color variables in mini player css

CustomApps/new-releases/index.js
i forgot to replace it in `new-releases`
=> fix(new-releases): update `viewportSelector` for `1.2.34` and higher

jsHelper/spicetifyWrapper.js
=> fix(wrapper/cards): change hook for `Default` card component

manifest.json
These extensions are broken when installed via marketplace and have weird behavior vs installed locally. I don't really wanna dig into it more
=> fix(manifest): remove borked extensions on marketplace

jsHelper/spicetifyWrapper.js
Fixes this green color text on every component on `1.2.35`
=> fix(getStyledClassName): add `$semanticColor` to included keys

jsHelper/spicetifyWrapper.js, src/apply/apply.go, src/cmd/config.go
~~This needs testing, please. I tried my best to test it out on both `extensions` and `custom apps` and tried all combinations but I feel like I forgot something.~~ What I have tried:
- extensions
- `spicetify config extensions "trashbin.js|fullAppDisplay.js"`
- `spicetify config extensions "trashbin.js|fullAppDisplay.js-"`
- `spicetify config extensions "trashbin.js-|fullAppDisplay.js"`
- `spicetify config extensions "trashbin.js-|fullAppDisplay.js-"` (I did not bother showing multiple values on removal)
- `spicetify config extensions "trashbin.js"`
- `spicetify config extensions "trashbin.js-"`
- custom apps
- `spicetify config custom_apps "lyrics-plus|stats"` 
- `spicetify config custom_apps "lyrics-plus|stats-"`
- `spicetify config custom_apps "lyrics-plus-|stats"`
- `spicetify config …
=> fix(config): check for duplicates when adding multiple values

jsHelper/spicetifyWrapper.js
THIS wasn't needed for `1.2.36` ._.
=> fix(getStyledClassName): add `paddingBottom` back to `customExactKeys`

CustomApps/lyrics-plus/index.js
…ranslateLyrics when hitting CACHE
Only fixes it when hitting CACHE, translateLyrics can *in theory* still be executed with outdated this.state.currentLyrics if tryServices resolves before the next component's rerender.
=> fix(lyrics-plus): force assign `currentLyrics` for cache

jsHelper/spicetifyWrapper.js
This matches the type of card better, `Default` is a barebone card (which is exposed via `reactComponentsUI.Card`), but the `Default` card we had before is more as of `FeatureCard` that's why I'm re-adding it as this one
Fixes https://github.com/Bergbok/Spicetify-Creations/issues/6
Fixes https://github.com/harbassan/spicetify-apps/issues/87
however this requires **changing _Default_ export to _FeatureCard_**
=> feat(wrapper/cards): re-add "Default" as `FeatureCard`

globals.d.ts, jsHelper/spicetifyWrapper.js
idk why this exists, it probably never worked after some update. just use `Spicetify.GraphQL.Definitions`
=> chore(wrapper): remove additional graphql getters

CustomApps/lyrics-plus/Utils.js, CustomApps/lyrics-plus/index.js
=> fix(translator): force setting `currentLyrics` on cache hit

Extensions/keyboardShortcut.js
changed the keybinding ctrl+up to increase the volume instead of decrease
=> fix(keyboardShortcut): correctly call functions for volume

CustomApps/lyrics-plus/ProviderLRCLIB.js, CustomApps/lyrics-plus/Providers.js, CustomApps/lyrics-plus/index.js, CustomApps/lyrics-plus/manifest.json
We can't really send spicetify version in `User-Agent` because it's dropped by Chromium but I left it in the code anyways 🤷‍♀️
resolves https://github.com/spicetify/cli/issues/3027
=> feat(lyrics-plus): add `lrclib` as a provider

CustomApps/lyrics-plus/ProviderNetease.js, CustomApps/lyrics-plus/Utils.js
lyrics time matching logic（For example:给我一首歌的时间）lyrics content mismatch
=> fix(lyrics-plus/netease): check correctly for songs

css-map.json
the reasoning for the brand new classname is spotify was using an unminified naming scheme for this element pre 1.2.40 - im simply re-adding their own classname they removed in the new update (playback-bar)
the reasoning for playback-progress-bar-container is self explanatory because in 1.2.40 playback-progressbar is now held within it
=> feat(css-map): add selectors for `1.2.40` playbar

src/preprocess/preprocess.go
According to @ohitstom, the `#242424` has become `#1f1f1f` in Spotify 1.2.43, thus we should replace both.
Sentry wasn't disabled for few(?) versions, so I updated the regex to work on new and old versions
=> fix(preprocess): disable sentry correctly and replace hex value

spicetify.go
The reason for this change is that people assume spicetify has an update when spotify is in stock. This will only work when spotify is backupable. This change was voted positively in spicetify server.
=> feat(update): run `backup apply` for stock spotify

CustomApps/new-releases/index.js
Restore `getArtistList` functionality by using `LibraryAPI.getContents` to perform the same operation that was previously handled by `LibraryAPI.getArtists` which no longer exists.
=> fix(new-releases): use `getContents` for `getArtistsList`

CustomApps/lyrics-plus/ProviderGenius.js
Fixes Genius (at least on 1.2.13)
=> fix(lyrics-plus): remove `encodeURIComponent` from `URLSearchParams` in genius provider

Extensions/popupLyrics.js
=> feat(popupLyrics): add lrclib provider 

css-map.json
Just fixed a single typo I noticed a little while back in the css-map ("search-searchCategory-cate**r**goryGrid" to "search-searchCategory-categoryGrid").
Saw it was still there and figured why not just fix it.
=> fix(css-map): just fixing a typo

jsHelper/spicetifyWrapper.js
tested on:
- 1.2.46
- 1.2.45
- 1.2.14
- 1.2.15
- 1.2.16
- 1.2.17
- 1.2.22
note:
im aware this approach is silly but to save rewriting the whole thing (or backporting more of v3) this approach works well and only took me 15 minutes lolol
=> feat(topbar): cross-version classname support

jsHelper/sidebarConfig.js
This PR is something tiny I noticed; despite the OS the user has, this error asks the user to open Powershell, this just replaced "Powershell" with "command prompt" to be OS-inclusive :)
=> chore(sidebarConfig): make phrasing more os inclusive

Extensions/fullAppDisplay.js
This makes the progress bar seekable like in the main window and aligns the control buttons, also, the control/progress bar will not extend into the lyrics anymore.
Additionally, the heart state is now fixed.
Before:
After:
https://github.com/user-attachments/assets/65031a68-b6f0-4a13-8f21-94c5c338386c
=> feat(fullAppDisplay): seekable progress and aligned buttons

Extensions/shuffle+.js
- Use `tracksV2` instead of `tracks` (if supported) when fetching album tracks
- Use hard-coded `queryArtistDiscographyAll` definition (due to Spotify v1.2.46; see [this PR](https://github.com/spicetify/cli/pull/3166))
=> fix(shuffle+): update GraphQL handling

Extensions/keyboardShortcut.js
The shortcut for switching to the previous track in [keyboardShortcut.js](https://github.com/spicetify/cli/blob/main/Extensions/keyboardShortcut.js) incorrectly calls **Spicetify.Player.prev**, a non-existent function, instead of **Spicetify.Player.back**. 
Solves #3122, which was closed without proper testing of the extension.
=> fix(keyboardShortcut): fix previous song shortcut not working

Extensions/trashbin.js
Added a export button to trashbin.js with working saving using the `window.showSaveFilePicker` method.
I also moved the old copy to clipboard logic to its own Copy button in case exporting fails
=> feat(trashbin): add a working export button

CustomApps/lyrics-plus/OptionsMenu.js, CustomApps/lyrics-plus/Pages.js, CustomApps/lyrics-plus/index.js
This PR adds a new option to the lyrics-plus app to choose the display mode of the lyrics translation:
- Replace: Actual behavior, replacing the original lyrics with its translation
- Below: Display the original lyrics, and the translated line below in a lower opacity (as in the screen)
I'm not used to work on JS projects so I still have some small issues about this PR:
- Translated lines and behavior are repeated for each `UnsyncedLyricsPage`, `SyncedExpandedLyricsPage` `SyncedLyricsPage` and I feel like this could be refactored.
- I didn't now how to name the new option, because there is already a `Display Mode` so any suggestion to rename the option is welcomed
- When changing said option, it doesn't reload the lyrics div. It works when disabling and re-enabling the translation though.
=> feat(lyrics-plus): allow to change display of lyrics translation

CustomApps/lyrics-plus/Pages.js
fixed the issue where the lyrics transition effect disappeared after patch #3297.
Unnecessary elements that were previously applied to the `<p>` tags have been modified to apply only to the parent `<div>`.
- Before
https://github.com/user-attachments/assets/337d212f-1c68-4c73-b21e-f479f4f07c97
- After
https://github.com/user-attachments/assets/fec94294-225f-472a-9fe2-e2926c6df3c9
=> fix(lyrics-plus): fix lyrics transition effect issue

CustomApps/lyrics-plus/OptionsMenu.js, CustomApps/lyrics-plus/Pages.js, CustomApps/lyrics-plus/Settings.js, CustomApps/lyrics-plus/Utils.js, CustomApps/lyrics-plus/index.js
If the lyrics are in Below-mode, the original lyrics or the translated lyrics can now be copy depending on the cursor position.
Additionally, when changing the `musixmatch translation language` in `lyrics plus config`, the page is now designed to re-load, allowing the translation feature to be used without switching to the next song.
And minor bugs were fixed, and unnecessary code was revised
- lyrics copy
https://github.com/user-attachments/assets/62d9a1d9-ba06-42ea-9bc9-2159109f0bbf
- musixmatch translation language change
https://github.com/user-attachments/assets/dda2972c-3a28-4c87-8bbf-8dac628c3f18
=> feat(lyrics-plus): translation Below-mode Individual copy implementation

CustomApps/lyrics-plus/OptionsMenu.js, CustomApps/lyrics-plus/Pages.js, CustomApps/lyrics-plus/Providers.js, CustomApps/lyrics-plus/Settings.js, CustomApps/lyrics-plus/Translator.js, CustomApps/lyrics-plus/Utils.js, CustomApps/lyrics-plus/index.js
- Introduced caching for converted lyrics and optimized the process by ensuring that only the selected `Display Mode` is applied instead of converting into all formats for a single language.  
- Improved code consistency between **Convert** and **Translation** functionalities.  
- If the lyrics are not in lockMode, the last used mode for that lyrics is stored in memory.
When the lyrics are reloaded, they will automatically switch to the saved mode.
- Previously, Spotify's official lyrics provider was displayed as `musixmatch`; this has now been changed to `Spotify`.
> Please let me know if you have any feedback on this.
- Added a function in **Lyrics Config** to clear cached lyrics from memory.  
- Added an option to delete individual locally saved lyrics.  
- Pressing the **Save Lyrics** …
=> feat(lyrics-plus): optimize lyrics convert performance & improved code quality

CustomApps/lyrics-plus/OptionsMenu.js, CustomApps/lyrics-plus/Settings.js
fix an issue where reverting to none after applying a translation caused an error.
=> fix(lyrics-plus): properly check for `none` value in trans lang

Extensions/popupLyrics.js
Implemented features that were previously available in lyrics-plus.
=> feat(popupLyrics): implement lyrics caching & Musixmatch token refresh

Extensions/popupLyrics.js
Fix the issue where lyrics were not updating when Spotify was in tray mode (minimized).
The callback of the `requestAnimationFrame()` function stops working when Spotify is switched to tray mode (minimized), making it impossible to check if `document.hidden` is true.
Due to the asynchronous nature of the callback, there are cases where `tick()` passes through before the callback is interrupted, causing `document.hidden` to return true and allowing lyrics to be updated in tray mode. However, the likelihood of this happening is too low.
So, I changed the structure to listen for the `visibilitychange` event.
=> fix(popupLyrics): update view in system tray mode

CustomApps/lyrics-plus/README.md
Updated Genius unavailability to match the settings warning in the app.
=> docs(lyrics-plus): update readme to warn Genius is disabled

jsHelper/spicetifyWrapper.js
PR fixes issue with line-clamp css property on playlist sidebar compact view (comparison on image)
=> fix: add `$lineClamp` key to styled components processing

CustomApps/lyrics-plus/Providers.js
The initial implementation by Netease only displayed a single line of translated text. This change allows for the display of two lines of lyrics, similar to Musixmatch.
=> feat(lyrics-plus/netease): implement below-mode for netease

css-map.json
Changed from key 'nw6rbs8R08fpPn7RWW2w' to 'BJ1zQ_ReY3QPaS7SW46s' due to the latest update from Spotify (Windows) 1.2.63.394.g126b0d89.
=> feat(css-map): update `lyrics-lyricsContent-lyric`

.github/workflows/build.yml, README.md
This pull request introduces changes to the GitHub Actions workflow configuration in `.github/workflows/build.yml`, focusing on adding a signing process for Windows executables and commenting out the release-triggering job for Homebrew and AUR. Below is a breakdown of the key changes:
* Added steps to upload unsigned Windows executables as artifacts, submit them for signing via SignPath, and copy back the signed executables. These steps are conditionally executed only for Windows builds.
=> feat(ci): add Windows signing process for executable in build workflow

Extensions/keyboardShortcut.js
This PR updates the keyboard shortcut for scrolling to the top of the page to follow Vim conventions more closely. Instead of using a single `g` key, users now need to press `gg` in sequence (like in Vim) to scroll to the top. This avoids accidental triggers and improves consistency with typical Vim keybindings.
=> feat(keyboardShortcut): change scroll top keybind
