- spicetify.go
> Fixed typo in "--quiet" flag check

- src/utils/utils.go
Gave fixing my own issue (#113) a try
> Check if dir exists and deleting it if so before symlinking app, fixes #113

- Extensions/fullAppDisplay.js
Allow the use of the F11 key to toggle the Full App Display.
> Allow toggling of Full App Display with the F11 key.

- Extensions/fullAppDisplay.js
- Extensions/newRelease.js
> Add option to show all artists in fullAppDisplay.js

- Extensions/shuffle+.js
Currently, 'Play with Shuffle+' is broken for folders that contain other folders or reside within another.
Returning `TypeError: Cannot read property 'map' of undefined` or `TypeError: Cannot read property 'rows' of undefined`, in the second case.
This PR fixes it by applying a recursive search.
> shuffle+: Add support for nested folders

- Extensions/fullAppDisplay.js
This change improves the animation performance when fading between songs.
> Disable backface-visibility in fullAppDisplay extension

- Extensions/shuffle+.js
Add "Add to Queue and Shuffle+" function.
Useful for shuffling multiple playlists and albums.
I created it for myself, but I hope you can integrate it.
> Improve shuffle+.js

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Fixes #774 by creating the bug report and feature request templates.
> Created Issue Templates

- jsHelper/spicetifyWrapper.js
Closes the Config popup when click is outside of the popup.
> Fix:Close popup when click is Outside

- CustomApps/lyrics-plus/index.js
- CustomApps/new-releases/index.js
- Extensions/fullAppDisplay.js
- Extensions/keyboardShortcut.js
- Extensions/loopyLoop.js
- Extensions/popupLyrics.js
- spicetify.go
- src/cmd/apply.go
- src/cmd/cmd.go
- src/cmd/patch.go
- src/utils/utils.go
This PR fixes some typos in code (variable names) and comments.
> Fix typos in code and comments

- Extensions/loopyLoop.js
> Fix extra parenthesis in loopyLoop causing error

- CustomApps/lyrics-plus/index.js
- Extensions/fullAppDisplay.js
- jsHelper/spicetifyWrapper.js
Fixes #1029 
- Lyrics Plus starting with no lyrics screen, only updating if the song changes
- Fix high CPU usage on fullAppDisplay
> Fix issues with 2.6.5

- CustomApps/lyrics-plus/Pages.js
> Fix Lyrics Plus Karaoke position error

- jsHelper/spicetifyWrapper.js
I assume related to changes in 1.1.69
> Fixes heart selector

- src/apply/apply.go
- src/cmd/apply.go
> NEW: export spicetify version to js

- css-map.json
From Spotify for Windows 1.1.76.447.g11f432d8
> CSS map: update 'more albums by artist' shelf

- Extensions/keyboardShortcut.js
> fix keyboard shortcut for queue button

- CustomApps/lyrics-plus/Pages.js
fixed lyrics.providedBy text bug on Lyrics plus.  #1422
> fix: lyrics.providedBy text bug on lyrics-plus

- CustomApps/lyrics-plus/Pages.js
> temporarily disable split display for genius

- Extensions/fullAppDisplay.js
> trim title after comma in fad

- install.sh
> fix: install message tip

- src/preprocess/preprocess.go
@afonsojramos Created a seperate branch for continuous patching of the hooks (overtime)
> fix: patch part of menu hook

- install.sh
> fix: specific version fetching in install script

- install.sh
>  chore: add bash_profile fallback for bash

- CustomApps/new-releases/index.js
Due to the CSS Change In 1.1.83+, The Song Cards Where Being Displayed Incorrectly.
> fix(New-Releases): fix cards being displayed incorrectly

- spicetify.go
- src/cmd/devtools.go
Update the `--help` output in accordance with #1613
> fix: modify filePath from .config to .cache

- src/apply/apply.go
- src/preprocess/preprocess.go
- `Spicetify.ReactDOM`
- React symbols undefined error
- Includes additional symbol fixes from @CharlieS1103
Lyrics Plus does not work, some type of javascript error I do not have time to investigate.
> Fix for Spotify 1.1.85

- Extensions/keyboardShortcut.js
Fixed the volume shortcuts as `origin` doesn't exist anymore, and made the step smaller - I feel it's nicer, you be the judge of that!
> fix(keyboardShortcut.js): volume api & steps

- src/preprocess/preprocess.go
Potentially fixes folder switches
Fixes #1609
> fix(rtl): disable one rtl removal

- install.ps1
- install_curl.ps1
- spicetify.go
- src/cmd/apply.go
- src/utils/path-utils.go
* change config directory location on windows to %appdata%\spicetify
* change spicetify installation directory on windows to %localappdata%\spicetify
* add migration (old spicetify location to new one) to installation scripts
* remove old spicetify location from Path
Resolves #1778
> feat(windows): change spicetify location

- src/utils/config.go
> fix(config): finding spotify on gentoo

- install.ps1
Detects Windows architecture on install.
Related to #1814
> feat(windows/install): detect architecture

- src/apply/apply.go
- src/cmd/cmd.go
Compatibility with/hotfix for 1.1.90.
> fix(apply): custom app regex for `1.1.90`

- src/apply/apply.go
Backwards compatibility for versions older than `1.1.90`
> fix(apply): backwards compatibility

- jsHelper/spicetifyWrapper.js
- src/preprocess/preprocess.go
Compatibility with/hotfix for Spotify `1.1.92`.
Backwards compatible & tested.
> fix(preprocess): platform hooks for `1.1.92`

- Extensions/fullAppDisplay.js
> feat(full-app-display): add like button

- src/cmd/devtools.go
- src/utils/config.go
> feat(devtools): add support for MSIX installations

- CustomApps/new-releases/Card.js
- CustomApps/new-releases/style.css
- CustomApps/reddit/Card.js
- CustomApps/reddit/style.css
spotify uses it like so, god knows why
> fix(CustomApps): play button styling

- src/apply/apply.go
- src/preprocess/preprocess.go
Resolves #1904
Compatibility with/hotfix for Spotify `1.1.93`.
Backwards compatible & tested.
> fix(preprocess): `1.1.93` hotfix

- src/preprocess/preprocess.go
Resolves #1733 
Issue seems to be from a library Spotify using, and since it hasn't been solved since, this is most likely deliberate and needed attention on our side
Seems to work fine, double checked every instance on xpui files and is valid also.
> fix(preprocess): crash on clicking `findFriendsButton`

- jsHelper/sidebarConfig.js
> fix(sidebarConfig): `personal-library` dragover styling

- jsHelper/spicetifyWrapper.js
> fix(topBar): reappend buttons on container removed

- jsHelper/expFeatures.js
Enables user the choice to change Experimental features that uses enums in addition to boolean types.
> feat(expFeatures): enable usage for enum type

- Extensions/fullAppDisplay.js
so people would stop asking the same question on support channel
> fix(fad): disable toggle if `Lyrics Plus` not applied

- jsHelper/expFeatures.js
idk this is just broken sometimes
> style(expFeatures): fix search bar styling

- CustomApps/reddit/style.css
- Extensions/fullAppDisplay.js
Compatibility with Spotify's new layout:
Also supports backwards compatibility for FAD.
> fix(Reddit): new layout compatibility

- src/cmd/devtools.go
> fix(devtools): searching for flatpak version

- css-map.json
found in `1.1.98.683.g5a3b77ad`
> chore(css-map): add main-connectBar-connectBar

- src/apply/apply.go
Resolves #2021 
Compatible with previous versions & tested
> fix(CustomApps): hotfix for `1.1.99`

- css-map.json
classes found in 1.1.99.878.g1e4ccc6e
> chore(css-map): update lyrics classes

- src/apply/apply.go
Fixes issues where custom apps that uses routes (like Marketplace Readme) was not working properly
> fix(apply): define custom app routes

- install.sh
> fix(install): add new line to file

- src/preprocess/preprocess.go
Update menu hooks for `1.2.0` and `1.2.1`
> fix(preprocess): update menu hooks

- .github/workflows/build.yml
For some reason this refuses to redirect/proxy from the old URL on my side so I'm just going to change it here. I made some server changes that broke some of my webserver stuff, sorry about that.
> fix(github/actions): AUR update

- CustomApps/lyrics-plus/Pages.js
- CustomApps/lyrics-plus/index.js
- CustomApps/lyrics-plus/style.css
Resolves #1993 
The file will be used until user changes song, and that support for karaoke is not yet available because I have never seen it working before lol
> feat(lyrics-plus): support for lrc files

- CustomApps/lyrics-plus/OptionsMenu.js
- CustomApps/lyrics-plus/index.js
> feat(lyrics-plus): remember song delay

- CustomApps/lyrics-plus/Pages.js
- CustomApps/lyrics-plus/index.js
Somehow I missed that my math was off 💀
Also included things I should have done/thought of before
> fix(lyrics-plus): various fixes to local lyrics

- CustomApps/lyrics-plus/style.css
> style(lyrics-plus): specify width for config button

- .github/workflows/build.yml
Adds action to bump the homebrew tap version on release
> feat(github/actions): add homebrew release step

- src/utils/watcher.go
> fix(macos): reload in watch

- CustomApps/lyrics-plus/Pages.js
- CustomApps/lyrics-plus/Utils.js
> fix(lyrics-plus): copy converted Japanese lyrics

- globals.d.ts
- src/preprocess/preprocess.go
Utilizing more stuff that Spotify uses
> feat: add `msTimeout` for `showNotification`

- install.ps1
> fix(windows/install): declare variable in order

- CustomApps/lyrics-plus/style.css
> fix(lyrics-plus): updated margins

- CustomApps/lyrics-plus/OptionsMenu.js
- CustomApps/lyrics-plus/ProviderNetease.js
- CustomApps/lyrics-plus/Providers.js
- CustomApps/lyrics-plus/index.js
Add Chinese translation option when this song has netease translation.
Maybe it can solve this issue: https://github.com/spicetify/spicetify-cli/issues/1411#issue-1104981280
> feat(lyrics-plus): add netease translation

- install.sh
> fix(install): add check for $ZDOTDIR

- CustomApps/lyrics-plus/style.css
Made that long div uncliable so it doesnt interfier when clicking the lyrics
> fix(lyrics-plus): make config container unclickable

- CustomApps/lyrics-plus/index.js
Apparently this is a thing I forgot to take account of:
> fix(lyrics-plus): remove ID3 tags from `.lrc`

- src/preprocess/preprocess.go
Minor stuff that's breaking Reddit and New Releases
> fix(preprocess): submenu hooks for `1.2.6`

- CustomApps/lyrics-plus/Pages.js
https://github.com/spicetify/spicetify-cli/issues/2012#issuecomment-1447964780
Tested with/without DevTools enabled.
> fix(lyrics-plus): copy on context menu

- Extensions/webnowplaying.js
Adds compatibility for new versions of WebNowPlaying for Rainmeter that changes communication protocol while maintaining compatibility with old versions.
> fix: add compatibility for webnowplaying-redux

- Extensions/shuffle+.js
- globals.d.ts
- jsHelper/spicetifyWrapper.js
> feat(wrapper): use icons in menu item

- CustomApps/lyrics-plus/Providers.js
- CustomApps/lyrics-plus/Settings.js
- CustomApps/lyrics-plus/Utils.js
- CustomApps/lyrics-plus/index.js
- CustomApps/lyrics-plus/style.css
In request of #2158.
Track link for cross-referrence: [505 - Arctic Monkeys](https://open.spotify.com/track/0BxE4FqsDD1Ot4YuBXwAPp?si=b513cf4d07f6469d)
> feat(lyrics-plus): save loaded lyrics & support for enhanced LRC

- CustomApps/lyrics-plus/Settings.js
- CustomApps/lyrics-plus/index.js
> fix(lyrics-plus): clear cache text

- jsHelper/expFeatures.js
If users were to install Spicetify for the first time, Experimental Features would default to **locally** assigned values, which can vary from remotely assigned ones given that a lot of them are used in production already.
This can create a problem where fresh Spicetify installation can make Spotify UX much different than it is without modification.
The issue can be replicated by removing the `spicetify-exp-features` `localStorage` item and restarting the client afterwards.
> fix(exp-features): use remote values in fresh install

- jsHelper/spicetifyWrapper.js
> fix(wrapper): button props for styled classes

- jsHelper/sidebarConfig.js
some stuff I didn't notice before
> fix(sidebar-config): YLX behavior

- globals.d.ts
- jsHelper/expFeatures.js
- jsHelper/spicetifyWrapper.js
- src/preprocess/preprocess.go
they broke platform hook again...
also clean up and update type definition
> fix: patch for `1.2.9`

- Extensions/bookmark.js
Show notification when users try to bookmark an invalid page (e.g. custom apps)
Also fixes styling and uses tippy for button
> fix(bookmark): show notification on error

- src/cmd/watch.go
solution found by @kyrie25
fixes #2246
> fix: remote debugging

- src/cmd/apply.go
> fix(updateTheme): don't exit when prop is blank

- src/utils/watcher.go
Resolves #2271 
Also moved away from deprecated packages
https://user-images.githubusercontent.com/77577746/232745451-d5f7e004-8df5-4e6c-8def-4d785b175884.mp4
> fix(watch): reload on asset change

- jsHelper/spicetifyWrapper.js
> feat(wrapper): changelog in update popup

- CustomApps/lyrics-plus/index.js
Simple fix to prominent color ID finding (fetchColors func) due to its order constantly changing.
Fixes #2220
> fix(lyrics-plus): colorful background

- jsHelper/spicetifyWrapper.js
little bug I found messing with libX
> fix(wrapper): append props with dynamic entries

- install.ps1
based on [Microsoft guidelines](https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/cmdlet-development-guidelines),  community [The PowerShell Best Practices and Style Guide](https://poshcode.gitbook.io/powershell-practice-and-style) and [PSScriptAnalyzer](https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer) warnings
> refactor(install.ps1): improve style

- install.ps1
> fix(windows/install): bring back missing arguments

- globals.d.ts
- jsHelper/spicetifyWrapper.js
Add interface for interacting with app title.
> feat(wrapper): add interface for app title

- css-map.json
> chore(css-map): update like button classes

- Extensions/trashbin.js
A simple settings menu for enabling/disabling trashbin and a way to export and import json structured localstorage items, resolves #2163.
> feat(trashbin): import/export & settings modal

- Extensions/trashbin.js
I got `NotAllowedError: Write permission denied.` when exporting, so i added a catch block with deprecated execCommand copy
> fix(trashbin): export config

- CustomApps/lyrics-plus/OptionsMenu.js
- CustomApps/lyrics-plus/index.js
Resolves #2318 
https://user-images.githubusercontent.com/77577746/236085062-1a356b56-6ef7-4281-b1aa-b4ad9a312467.mp4
https://user-images.githubusercontent.com/77577746/236085107-7de1f44d-e15d-4c80-a8b7-70880dada4a0.mp4
> fix(lyrics-plus): update lyrics on queue spam & lock mode

- css-map.json
Found in Spotify 1.2.11.914.gd3175972
> chore(css-map): add root classes

- globals.d.ts
- jsHelper/spicetifyWrapper.js
Filter definitions by types for ease of usage
> feat(graphql): filter definition types

- CustomApps/lyrics-plus/PlaybarButton.js
- Extensions/trashbin.js
- globals.d.ts
- jsHelper/spicetifyWrapper.js
Adds a class to create a button next to the track info
Returns Trashbin widget functionality similar to v1 and some other fixes
> feat(playbar): add `Widget`

- CustomApps/new-releases/index.js
Fix issue where card is duplicating itself on dismiss
> fix(new-release): render duplicate card on dismiss

- Extensions/trashbin.js
Only display widget on tracks, same as context menu item
> fix(trashbin): display widget on supported URI type

- jsHelper/spicetifyWrapper.js
Use proper add button styling so buttons have enough breathing room ig
> fix(widget): spacing

- Extensions/trashbin.js
Fix bug where widget appears after song change on disabled
> fix(trashbin): disable widget on song change

- jsHelper/spicetifyWrapper.js
- src/apply/apply.go
- src/cmd/cmd.go
- src/preprocess/preprocess.go
Patch Library X custom app & plethora of hooks.
Tested from `1.2.1`, have not tested below.
Also add conditions to prevent Spotify from completely breaking when sidebar item is not found.
> fix: `1.2.13` hotfix

- jsHelper/spicetifyWrapper.js
```js
new Spicetify.Topbar.Button("test", "download", () => {console.log("hi")}, false, true)
```
> feat(wrapper/topbar): append button on right

- src/apply/apply.go
- src/preprocess/preprocess.go
Also disables warning message for legacy layout since it is permanently deprecated
> fix: hotpatch for `1.2.14`

- CustomApps/lyrics-plus/style.css
<details open>
<summary>Visual</summary>
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</details>
<details open>
<summary>Technical</summary>
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</details>
removes scrollbar etc, please test before accepting however i did go over everything i could think of (fullscreen, no blur/overlay, no lyrics, different text sizes, compact vs non compact etc.)
> fix(lyrics-plus): absolute positioning in container

- Extensions/fullAppDisplay.js
As title suggests.
Just seems really annoying when full screen toggle is meant to hide window components but the cursor is still around
> feat(fad): hide cursor on fullscreen & inactivity

- src/preprocess/preprocess.go
i was not aware this was broken until now
> fix(panel): patch for `1.2.14`

- CustomApps/lyrics-plus/Utils.js
- CustomApps/lyrics-plus/style.css
> fix(lyrics-plus): ignore lang check on none/Genius

- jsHelper/spicetifyWrapper.js
spotify smh (breaks on 1.2.13)
> fix(wrapper/functionModules): handle errors

- CustomApps/lyrics-plus/Pages.js
- CustomApps/lyrics-plus/index.js
Just like the Synced and Unsynced pages, we implemented lyric copying on the Genius pages.
https://github.com/spicetify/spicetify-cli/assets/91320047/1417f890-7a40-4349-9fe1-41d768bc2525
> feat(lyrics-plus): copy Genius page lyrics

- CustomApps/lyrics-plus/Settings.js
- CustomApps/lyrics-plus/Utils.js
Get new Musixmatch token on demand to circumvent captcha when using the default token.
https://github.com/spicetify/spicetify-cli/assets/77577746/880750b4-d130-4853-9c08-d27836601caa
> feat(lyrics-plus): refresh token on demand

- globals.d.ts
- jsHelper/spicetifyWrapper.js
https://github.com/spicetify/spicetify-cli/assets/77577746/5f44ea15-1fe3-442e-a6e3-c0767daa2c17
> feat(react-component): add `Slider`

- CustomApps/reddit/Card.js
> fix(reddit): type check subtitle

- globals.d.ts
- jsHelper/spicetifyWrapper.js
> feat: expose `extractColorPreset` & `Color`

- jsHelper/spicetifyWrapper.js
Fix panels reporting incorrect active state in client launch.
> fix(panel): launch render state

- jsHelper/spicetifyWrapper.js
- src/preprocess/preprocess.go
> fix(panel): initial render state

- Extensions/shuffle+.js
> fix(shuffle+): add context support for Queue

- src/preprocess/preprocess.go
> fix(preprocess): patch for `1.2.20`

- src/utils/config.go
> feat(utils/config): support semicolon in config values

- CustomApps/new-releases/style.css
Overrides spotifys setting of pointer events to none on main-card
resolves #2581
> fix(new-releases): pointer events override

- CustomApps/lyrics-plus/style.css
> fix(lyrics-plus): hide synced lyrics container overflow-x

- css-map.json
> chore(css-map): map `lyrics-lyricsContent-text`

- src/preprocess/preprocess.go
> feat: stop sending the events to gabo-service

- css-map.json
- jsHelper/spicetifyWrapper.js
resolves #2610
this should also include backwards compatibility for our playbar button api, as well as amending its classlist.
edit: I didn't notice sunset had drafted a pr to fix the same issue, however this covers his changes and the others outlined in my original issue #2610
> fix(wrapper): styled component filters

- src/preprocess/preprocess.go
> feat(preprocess): prevent logging in localStorage

- src/preprocess/preprocess.go
thanks to @surfbryce for this regex
> fix(preprocess/disableLogging): match function in older versions

- spicetify.go
- src/apply/apply.go
- src/preprocess/preprocess.go
- src/status/backup/backup.go
- src/status/spotify/spotify.go
There were some unused stub functions as well that we might as well delete.
> fix: further static analysis fixes

- CustomApps/lyrics-plus/ProviderNetease.js
- Extensions/popupLyrics.js
The PyNCM api you were using seems to have stopped working. Instead, neteaseapi worked fine again, revert #2508 and #2516 commit.
> revert(lyrics-plus): netease api

- spicetify.go
> fix(spicetify): `update` & `upgrade` commands

- src/cmd/update.go
it doesn't look like anyone else is going to do this, so yeah
fixes #2655
> feat(cmd/update): remove redundant code

- spicetify.go
> fix: correct spotifyPath inside update cmd

- jsHelper/spicetifyWrapper.js
- src/preprocess/preprocess.go
removed private methods and props from the `Spicetify.Snackbar` object
added `SnackbarProvider` and `useSnackbar`
> feat: enhance snackbar exposition

- globals.d.ts
- jsHelper/spicetifyWrapper.js
Information about removing it was sent in discord server to developers before creating this pull request
> feat: remove compatibility `track` property

- jsHelper/spicetifyWrapper.js
this thing:
tested versions:
docs & types later
> feat(wrapper): add `Toggle` ReactComponent

- jsHelper/spicetifyWrapper.js
and stop dispatching `onprogress` if item is paused
> refactor(wrapper): use `update` event for generating `Player` events

- src/cmd/apply.go
> feat(apply): refresh theme even if `current_theme` is blank

- .github/workflows/prettier.yml
https://github.com/spicetify/spicetify-cli/pull/2719#issuecomment-1851604429
> feat(workflows): use `dry` option for prettier action

- jsHelper/spicetifyWrapper.js
rn the assignment in the `vendor~xpui.js` overwrites `Spicetify.Snackbar`
> fix(wrapper): wait for snackbar exposition before adding modules to it

- install.ps1
> style(install): remove empty lines

- jsHelper/spicetifyWrapper.js
it is actually just card header + link and nothing more lol
> feat(wrapper): remove `Base` card React component

- jsHelper/spicetifyWrapper.js
Resolves #2750
This PR also fixes `DragHandler` availability from `1.2.1` to `1.2.8` and `extractColorPreset` on `1.2.5`
biome*: https://biomejs.dev/linter/rules
> feat: apply biome suggestions and fix few hooks

- CustomApps/lyrics-plus/Utils.js
- Extensions/fullAppDisplay.js
> fix: refactor `Utils` and change prop in `fullAppDisplay`

- Extensions/popupLyrics.js
There was an issue with the spacing between letters in the Korean and Japanese lyrics, so this was corrected.
- Before
- After
> fix(popupLyrics): fix letter spacing issue in some lyrics

- src/cmd/apply.go
- src/cmd/backup.go
сauses **_a lot_** of problems, being almost useless
> feat(cmd): don't allow to proceed if backup is outdated

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- install.sh
@KaKi87 please let me know if that one works fine on your system ^^
Fixes #2774, fixes #2591, fixes #2584, fixes #2283
> feat(install): make script POSIX compliant

- jsHelper/spicetifyWrapper.js
- src/preprocess/preprocess.go
tested with spotify 1.2.0, 1.2.5, 1.2.8, 1.2.13, 1.2.17, 1.2.23, 1.2.30
> feat: expose `ContextMenu` React component via wrapper

- jsHelper/spicetifyWrapper.js
- src/preprocess/preprocess.go
fixes https://github.com/spicetify/spicetify-cli/issues/2869
> fix(logging): return necessary values

- CustomApps/lyrics-plus/ProviderNetease.js
- CustomApps/lyrics-plus/Providers.js
- Extensions/popupLyrics.js
I think you missed it while editing #2859.
> fix: use correct url to spotify & fix netease

- CustomApps/lyrics-plus/index.js
- src/apply/apply.go
- src/cmd/apply.go
- src/cmd/cmd.go
there's literally no need for it
> chore: remove information of supported spotify ver

- CustomApps/lyrics-plus/OptionsMenu.js
- CustomApps/lyrics-plus/ProviderNetease.js
- CustomApps/lyrics-plus/Settings.js
- CustomApps/lyrics-plus/TabBar.js
- CustomApps/lyrics-plus/index.js
- CustomApps/new-releases/index.js
- CustomApps/reddit/TabBar.js
- Extensions/loopyLoop.js
- Extensions/popupLyrics.js
- Extensions/webnowplaying.js
- biome.json
- jsHelper/spicetifyWrapper.js
fixes something something rare. just buy better cpu at this point
> fix(wrapper): assign `Player.data` in cache after becoming available

- CustomApps/lyrics-plus/Settings.js
- CustomApps/lyrics-plus/TabBar.js
- CustomApps/lyrics-plus/index.js
since I was rewriting `links` variable, it always different every-time, causing the second `useEffect` to re-render this component very frequently. I changed it, and it should work correctly now.
I also optimized these functions because they took around ~600ms to execute anyway
fixes https://github.com/spicetify/spicetify-cli/issues/2877
> fix(lyrics-plus): prevent re-rendering `TabBar` frequently

- Extensions/bookmark.js
- Extensions/loopyLoop.js
> fix(extensions): migrate to react menuItems

- jsHelper/spicetifyWrapper.js
> fix(topbar): match spotify styling

- jsHelper/spicetifyWrapper.js
> fix(wrapper/MenuItem): set `isEnabled` not `_isEnabled`

- CustomApps/lyrics-plus/Pages.js
> fix(lyrics-plus): access props when copying translated lyrics

- css-map.json
- jsHelper/expFeatures.js
- jsHelper/spicetifyWrapper.js
- src/apply/apply.go
- src/utils/utils.go
It’s a backport from v3
Co-authored-by: Delusoire <deluso7re@outlook.com>
> feat: add support for new global navbar

- jsHelper/spicetifyWrapper.js
Fixes #2925
It doesn't need to be more beautiful or anything...
> fix(wrapper): adapt `checkForUpdate` to new changelog

- src/cmd/update.go
> feat(cmd/update): add support for `arm64`

- install.ps1
See: https://github.com/spicetify/spicetify-cli/pull/2956
> feat(windows/install): add help text for `?` choices

- jsHelper/spicetifyWrapper.js
- src/apply/apply.go
- src/preprocess/preprocess.go
- src/utils/utils.go
Fixes https://github.com/spicetify/spicetify-cli/issues/2955
> fix: adapt regexes for `1.2.35`

- CustomApps/lyrics-plus/index.js
This doesn't really break lyrics-plus in general but it would be nice if it would be updated
> fix(lyrics-plus): add second selector for viewport

- jsHelper/spicetifyWrapper.js
Didn't notice it yesterday oopsie
> fix(getStyledClassName): remove `$` from `childrenProps`

- jsHelper/spicetifyWrapper.js
> fix(wrapper): revert `CardImage` component

- Extensions/shuffle+.js
> fix(shuffle+): lower limit & bring back `queryArtistOverview`

- css-map.json
resolves ohitstom/spicetify-extensions#12
^ doubt this works but hey ho
> feat(css-map): 1.2.36 tracklist row hearts

- jsHelper/spicetifyWrapper.js
fixes productstate on `1.2.37`
> fix(wrapper/platform): assign product state to old prop

- Extensions/keyboardShortcut.js
> fix(keyboard-shortcut): some shortcuts that stopped working

- src/preprocess/preprocess.go
tested on:
- 1.2.38
- 1.2.33
Going to be away from pc for a couple days please handle any requested changes yourselves, i apologize for the inconvenience !
> fix(preprocess): enqueueCustomSnackbar for v1.2.38

- CustomApps/lyrics-plus/Providers.js
- Extensions/popupLyrics.js
Addresses previously raised issue #3056.
It appears that the API `https://spclient.wg.spotify.com/lyrics/v1/track/` currently in use no longer works. Instead, 
I solved the problem by using the `https://spclient.wg.spotify.com/color-lyrics/v2/track/` API  used in the official lyrics.
> fix: spotify lyrics request error fix

- Extensions/keyboardShortcut.js
> fix(keyboardShortcut): update focus selector

- Extensions/trashbin.js
> fix(trashbin): look for different element

- CustomApps/lyrics-plus/Pages.js
- CustomApps/lyrics-plus/style.css
Makes it look a bit more like Apple Music, kind of.
Preview: 
https://github.com/user-attachments/assets/bbe42219-517c-4163-b48a-470050970906
> style(lyrics-plus): adjust lyric animation in `karaoke` mode

- jsHelper/spicetifyWrapper.js
Changed the string from "onStepBackward" to "progressBarRef", tested on other supported versions.
> fix(wrapper): replace find string for `Slider` component

- jsHelper/spicetifyWrapper.js
Suggested solution for waiting for lazy-loaded modules. If there are required changes, please commit them directly onto the branch
> fix(wrapper): wait until all modules loaded

- css-map.json
- jsHelper/homeConfig.js
- src/apply/apply.go
- src/preprocess/preprocess.go
tested on 1.2.45, 1.2.44, and 1.2.41
> fix(home-config): support up to 1.2.45

- README.md
> fix: svg url in readme.md

- CustomApps/lyrics-plus/ProviderNetease.js
- CustomApps/lyrics-plus/Utils.js
- CustomApps/lyrics-plus/style.css
- CustomApps/new-releases/style.css
- Extensions/bookmark.js
- Extensions/fullAppDisplay.js
- Extensions/popupLyrics.js
- biome.json
- jsHelper/spicetifyWrapper.js
https://biomejs.dev/guides/upgrade-to-biome-v2/#the-import-organizer-sorts-differently-the-imports
> style(biome): update schema

- globals.d.ts
- jsHelper/sidebarConfig.js
Got tired of the errors in DevTools ngl
> fix(sidebarConfig): wait for snackbar & new props

- src/apply/apply.go
- src/utils/utils.go
> fix(apply): support for `1.2.70`
